// Generated by kibo from service. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Service.dsm.json by kibo-1.2.10.jar

/**
 * Remote attachment function-pool clients (over ServiceRemote) for service.
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as d from "./data.js";

// PlayerModel
export class PlayerModel {

    private readonly serviceRemote: dsviper.ServiceRemote;

    constructor(serviceRemote: dsviper.ServiceRemote) {
        this.serviceRemote = serviceRemote;
    }

    isAvailable(): boolean {
        return this.serviceRemote.attachmentFunctionPoolFuncs("PlayerModel") !== undefined;
    }

    create(attachmentMutating: dsviper.AttachmentMutating, nickname: string, level: d.Demo_Level): d.Demo_PlayerKey {
        const result = this.serviceRemote.attachmentFunctionPoolFunc("PlayerModel", "create").call(attachmentMutating, new dsviper.ValueString(nickname), level.vprValue) as unknown as dsviper.OutputValue;
        return d.Demo_PlayerKey.wrap(result);
    }
    hasPlayer(attachmentMutating: dsviper.AttachmentMutating, nickname: string): d.Optional_Demo_PlayerKey {
        const result = this.serviceRemote.attachmentFunctionPoolFunc("PlayerModel", "has_player").call(attachmentMutating, new dsviper.ValueString(nickname)) as unknown as dsviper.OutputValue;
        return d.Optional_Demo_PlayerKey.wrap(result);
    }
}
