// Generated by kibo from service. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Service.dsm.json by kibo-1.2.10.jar

/**
 * Getters and setters for attachments defined for service.
 * One exported object per attachment, with short methods (get/set/has/...).
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as mp from "./path.js";
import * as mt from "./value_type.js";
import * as d from "./data.js";

// Namespace Demo
// attachment<Player, PlayerProperty> Demo::property
export const player_Property = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Demo_PlayerKey {
        const attachment = mt.attachment_Demo_Player_Property();
        return new d.Set_Demo_PlayerKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Demo_PlayerKey, d.Set_Demo_PlayerKey, d.Set_Demo_PlayerKey, d.Set_Demo_PlayerKey] {
        const attachment = mt.attachment_Demo_Player_Property();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Demo_PlayerKey(added), new d.Set_Demo_PlayerKey(removed), new d.Set_Demo_PlayerKey(different), new d.Set_Demo_PlayerKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Demo_PlayerKey): boolean {
        const attachment = mt.attachment_Demo_Player_Property();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Demo_PlayerKey): d.Optional_Demo_PlayerProperty {
        const attachment = mt.attachment_Demo_Player_Property();
        return new d.Optional_Demo_PlayerProperty(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Demo_PlayerKey, value: d.Demo_PlayerProperty): void {
        const attachment = mt.attachment_Demo_Player_Property();
        attachmentMutating.set(attachment, key.vprValue, value.vprValue);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Demo_PlayerKey, value: d.Demo_PlayerProperty, recursive: boolean = false): void {
        const attachment = mt.attachment_Demo_Player_Property();
        attachmentMutating.diff(attachment, key.vprValue, value.vprValue, recursive);
    },

    setNickname(attachmentMutating: dsviper.AttachmentMutating, key: d.Demo_PlayerKey, value: string): void {
        const attachment = mt.attachment_Demo_Player_Property();
        attachmentMutating.update(attachment, key.vprValue, mp.Demo_Path_PlayerProperty.nickname, value);
    },

    setLevel(attachmentMutating: dsviper.AttachmentMutating, key: d.Demo_PlayerKey, value: d.Demo_Level): void {
        const attachment = mt.attachment_Demo_Player_Property();
        attachmentMutating.update(attachment, key.vprValue, mp.Demo_Path_PlayerProperty.level, value.vprValue);
    },


    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Demo_PlayerKey, d.Demo_PlayerProperty]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};
