// Generated by kibo from service. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Service.dsm.json by kibo-1.2.10.jar

/**
 * TypeScript classes for concepts, clubs, enums, structs and containers of service.
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as mt from "./value_type.js";
import * as md from "./definitions.js";

export class Proxy<V extends dsviper.Value = dsviper.Value> {

    readonly vprValue: V;

    constructor(vprValue: V) {
        this.vprValue = vprValue;
    }

    equals(other: Proxy): boolean {
        return this.vprValue.equals(other.vprValue);
    }

    compareTo(other: Proxy): number {
        return this.vprValue.compare(other.vprValue);
    }

    toString(): string {
        return this.vprValue.toString();
    }

    hexdigest(): string {
        return dsviper.Value.hexdigest(this.vprValue);
    }

    encode(streamCodecInstancing?: dsviper.StreamCodecInstancing): dsviper.ValueBlob {
        return dsviper.Value.encode(this.vprValue, streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY);
    }

    write(streamWriting: dsviper.StreamWriting): void {
        dsviper.Value.write(this.vprValue, streamWriting);
    }
}

// AnyConceptKey
export class AnyConceptKey extends Proxy<dsviper.ValueKey> {

    constructor(value: dsviper.ValueKey) {
        super(value);
    }

    static wrap(value: dsviper.OutputValue): AnyConceptKey {
        return new AnyConceptKey(dsviper.ValueKey.cast(value as dsviper.Value));
    }

    instanceId(): dsviper.ValueUUId {
        return this.vprValue.instanceId();
    }

    runtimeId(): dsviper.ValueUUId {
        return this.vprValue.typeConcept().runtimeId();
    }

    isValid(): boolean {
        return this.instanceId().isValid();
    }

    isKnown(): boolean {
        const rid = this.runtimeId();
        return [md.RuntimeIds.Demo_Player].some((id) => rid.equals(id));
    }

    description(): string {
        const rid = this.runtimeId();
        const instance = this.instanceId().encoded();
        if (rid.equals(md.RuntimeIds.Demo_Player)) { return `${instance}:AnyConceptKey(Demo::PlayerKey)`; }
        return `${instance}:AnyConceptKey(${rid.encoded()})`;
    }

    toString(): string {
        return this.description();
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): AnyConceptKey {
        const value = dsviper.ValueKey.cast(dsviper.Value.decode(blob, mt.type_AnyConceptKey(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new AnyConceptKey(value);
    }
}

// Namespace Demo
// concept Demo::PlayerKey
export class Demo_PlayerKey extends Proxy<dsviper.ValueKey> {

    constructor(identifier: dsviper.ValueKey | dsviper.ValueUUId | string) {
        if (identifier instanceof dsviper.ValueKey) {
            super(identifier);
        } else if (identifier instanceof dsviper.ValueUUId || typeof identifier === "string") {
            super(dsviper.ValueKey.create(mt.type_check_Demo_PlayerKey(), identifier));
        } else {
            throw new TypeError("identifier must be a ValueKey, a ValueUUId or a string");
        }
    }

    static wrap(value: dsviper.OutputValue): Demo_PlayerKey {
        return new Demo_PlayerKey(dsviper.ValueKey.cast(value as dsviper.Value));
    }

    static create(): Demo_PlayerKey {
        return new Demo_PlayerKey(dsviper.ValueUUId.create());
    }

    isKnown(): boolean {
        const rid = this.runtimeId();
        return [md.RuntimeIds.Demo_Player].some((id) => rid.equals(id));
    }

    description(): string {
        const rid = this.runtimeId();
        const instance = this.instanceId().encoded();
        if (rid.equals(md.RuntimeIds.Demo_Player)) { return `${instance}:Demo::PlayerKey`; }
        return `${instance}:Demo::PlayerKey(${rid.encoded()})`;
    }

    toString(): string {
        return this.description();
    }

    static fromAnyConceptKey(key: AnyConceptKey): Demo_PlayerKey | null {
        const rid = key.runtimeId();
        if (rid.equals(md.RuntimeIds.Demo_Player)) {
            return new Demo_PlayerKey(key.instanceId());
        }
        return null;
    }

    toAnyConceptKey(): AnyConceptKey {
        return new AnyConceptKey(this.vprValue.toAnyConceptKey());
    }

    instanceId(): dsviper.ValueUUId {
        return this.vprValue.instanceId();
    }

    runtimeId(): dsviper.ValueUUId {
        return this.vprValue.typeConcept().runtimeId();
    }

    isValid(): boolean {
        return this.instanceId().isValid();
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): Demo_PlayerKey {
        const value = dsviper.ValueKey.cast(dsviper.Value.decode(blob, mt.type_Demo_PlayerKey(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new Demo_PlayerKey(value);
    }
}

// enum Demo::Level
export class Demo_Level extends Proxy<dsviper.ValueEnumeration> {

    constructor(value: dsviper.ValueEnumeration) {
        super(value);
    }

    static wrap(value: dsviper.OutputValue): Demo_Level {
        return new Demo_Level(dsviper.ValueEnumeration.cast(value as dsviper.Value));
    }

    name(): string {
        return this.vprValue.name();
    }

    private static _BEGINNER: Demo_Level | null = null;
    static get BEGINNER(): Demo_Level {
        if (Demo_Level._BEGINNER === null) {
            Demo_Level._BEGINNER = new Demo_Level(new dsviper.ValueEnumeration(mt.type_Demo_Level(), "beginner"));
        }
        return Demo_Level._BEGINNER;
    }
    private static _INTERMEDIATE: Demo_Level | null = null;
    static get INTERMEDIATE(): Demo_Level {
        if (Demo_Level._INTERMEDIATE === null) {
            Demo_Level._INTERMEDIATE = new Demo_Level(new dsviper.ValueEnumeration(mt.type_Demo_Level(), "intermediate"));
        }
        return Demo_Level._INTERMEDIATE;
    }
    private static _EXPERT: Demo_Level | null = null;
    static get EXPERT(): Demo_Level {
        if (Demo_Level._EXPERT === null) {
            Demo_Level._EXPERT = new Demo_Level(new dsviper.ValueEnumeration(mt.type_Demo_Level(), "expert"));
        }
        return Demo_Level._EXPERT;
    }

    static fromStr(name: string): Demo_Level {
        switch (name) {
            case "beginner":
                return Demo_Level.BEGINNER;
            case "intermediate":
                return Demo_Level.INTERMEDIATE;
            case "expert":
                return Demo_Level.EXPERT;
            default:
                throw new Error(`unknown enumeration case ${name}`);
        }
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): Demo_Level {
        const value = dsviper.ValueEnumeration.cast(dsviper.Value.decode(blob, mt.type_Demo_Level(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new Demo_Level(value);
    }
}

// struct Demo::PlayerProperty
export class Demo_PlayerProperty extends Proxy<dsviper.ValueStructure> {

    constructor(value?: dsviper.ValueStructure | Record<string, dsviper.InputValue>) {
        if (value instanceof dsviper.ValueStructure) {
            super(value);
        } else {
            super(new dsviper.ValueStructure(mt.type_Demo_PlayerProperty(), value));
        }
    }

    static wrap(value: dsviper.OutputValue): Demo_PlayerProperty {
        return new Demo_PlayerProperty(dsviper.ValueStructure.cast(value as dsviper.Value));
    }

    get nickname(): string {
        return this.vprValue.at("nickname") as string;
    }

    set nickname(value: string) {
        this.vprValue.set("nickname", value);
    }
    get level(): Demo_Level {
        return Demo_Level.wrap(this.vprValue.at("level"));
    }

    set level(value: Demo_Level) {
        this.vprValue.set("level", value.vprValue);
    }

    copy(): Demo_PlayerProperty {
        return new Demo_PlayerProperty(this.vprValue.copy());
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): Demo_PlayerProperty {
        const value = dsviper.ValueStructure.cast(dsviper.Value.decode(blob, mt.type_Demo_PlayerProperty(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new Demo_PlayerProperty(value);
    }
}

// struct Demo::Vector3
export class Demo_Vector3 extends Proxy<dsviper.ValueStructure> {

    constructor(value?: dsviper.ValueStructure | Record<string, dsviper.InputValue>) {
        if (value instanceof dsviper.ValueStructure) {
            super(value);
        } else {
            super(new dsviper.ValueStructure(mt.type_Demo_Vector3(), value));
        }
    }

    static wrap(value: dsviper.OutputValue): Demo_Vector3 {
        return new Demo_Vector3(dsviper.ValueStructure.cast(value as dsviper.Value));
    }

    get x(): number {
        return this.vprValue.at("x") as number;
    }

    set x(value: number) {
        this.vprValue.set("x", value);
    }
    get y(): number {
        return this.vprValue.at("y") as number;
    }

    set y(value: number) {
        this.vprValue.set("y", value);
    }
    get z(): number {
        return this.vprValue.at("z") as number;
    }

    set z(value: number) {
        this.vprValue.set("z", value);
    }

    copy(): Demo_Vector3 {
        return new Demo_Vector3(this.vprValue.copy());
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): Demo_Vector3 {
        const value = dsviper.ValueStructure.cast(dsviper.Value.decode(blob, mt.type_Demo_Vector3(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new Demo_Vector3(value);
    }
}

// optional<any_concept>
export class Optional_AnyConceptKey extends Proxy<dsviper.ValueOptional> {

    constructor(value?: dsviper.ValueOptional | AnyConceptKey | null) {
        if (value instanceof dsviper.ValueOptional) {
            super(value);
        } else if (value === null || value === undefined) {
            super(new dsviper.ValueOptional(mt.type_optional_AnyConceptKey()));
        } else {
            super(new dsviper.ValueOptional(mt.type_optional_AnyConceptKey(), value.vprValue));
        }
    }

    static wrap(value: dsviper.OutputValue): Optional_AnyConceptKey {
        return new Optional_AnyConceptKey(dsviper.ValueOptional.cast(value as dsviper.Value));
    }

    isNil(): boolean {
        return this.vprValue.isNil();
    }

    unwrap(): AnyConceptKey {
        return AnyConceptKey.wrap(this.vprValue.unwrap());
    }

    wrap(value: AnyConceptKey): void {
        this.vprValue.wrap(value.vprValue);
    }

    get(defaultValue?: AnyConceptKey): AnyConceptKey {
        return AnyConceptKey.wrap(this.vprValue.get(defaultValue === undefined ? undefined : defaultValue.vprValue));
    }

    copy(): Optional_AnyConceptKey {
        return new Optional_AnyConceptKey(this.vprValue.copy());
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): Optional_AnyConceptKey {
        const value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_AnyConceptKey(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new Optional_AnyConceptKey(value);
    }
}

// optional<key<Demo::Player>>
export class Optional_Demo_PlayerKey extends Proxy<dsviper.ValueOptional> {

    constructor(value?: dsviper.ValueOptional | Demo_PlayerKey | null) {
        if (value instanceof dsviper.ValueOptional) {
            super(value);
        } else if (value === null || value === undefined) {
            super(new dsviper.ValueOptional(mt.type_optional_Demo_PlayerKey()));
        } else {
            super(new dsviper.ValueOptional(mt.type_optional_Demo_PlayerKey(), value.vprValue));
        }
    }

    static wrap(value: dsviper.OutputValue): Optional_Demo_PlayerKey {
        return new Optional_Demo_PlayerKey(dsviper.ValueOptional.cast(value as dsviper.Value));
    }

    isNil(): boolean {
        return this.vprValue.isNil();
    }

    unwrap(): Demo_PlayerKey {
        return Demo_PlayerKey.wrap(this.vprValue.unwrap());
    }

    wrap(value: Demo_PlayerKey): void {
        this.vprValue.wrap(value.vprValue);
    }

    get(defaultValue?: Demo_PlayerKey): Demo_PlayerKey {
        return Demo_PlayerKey.wrap(this.vprValue.get(defaultValue === undefined ? undefined : defaultValue.vprValue));
    }

    copy(): Optional_Demo_PlayerKey {
        return new Optional_Demo_PlayerKey(this.vprValue.copy());
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): Optional_Demo_PlayerKey {
        const value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_Demo_PlayerKey(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new Optional_Demo_PlayerKey(value);
    }
}

// optional<Demo::PlayerProperty>
export class Optional_Demo_PlayerProperty extends Proxy<dsviper.ValueOptional> {

    constructor(value?: dsviper.ValueOptional | Demo_PlayerProperty | null) {
        if (value instanceof dsviper.ValueOptional) {
            super(value);
        } else if (value === null || value === undefined) {
            super(new dsviper.ValueOptional(mt.type_optional_Demo_PlayerProperty()));
        } else {
            super(new dsviper.ValueOptional(mt.type_optional_Demo_PlayerProperty(), value.vprValue));
        }
    }

    static wrap(value: dsviper.OutputValue): Optional_Demo_PlayerProperty {
        return new Optional_Demo_PlayerProperty(dsviper.ValueOptional.cast(value as dsviper.Value));
    }

    isNil(): boolean {
        return this.vprValue.isNil();
    }

    unwrap(): Demo_PlayerProperty {
        return Demo_PlayerProperty.wrap(this.vprValue.unwrap());
    }

    wrap(value: Demo_PlayerProperty): void {
        this.vprValue.wrap(value.vprValue);
    }

    get(defaultValue?: Demo_PlayerProperty): Demo_PlayerProperty {
        return Demo_PlayerProperty.wrap(this.vprValue.get(defaultValue === undefined ? undefined : defaultValue.vprValue));
    }

    copy(): Optional_Demo_PlayerProperty {
        return new Optional_Demo_PlayerProperty(this.vprValue.copy());
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): Optional_Demo_PlayerProperty {
        const value = dsviper.ValueOptional.cast(dsviper.Value.decode(blob, mt.type_optional_Demo_PlayerProperty(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new Optional_Demo_PlayerProperty(value);
    }
}

// set<Demo::Player>
export class Set_Demo_PlayerKey extends Proxy<dsviper.ValueSet> {

    constructor(value?: dsviper.ValueSet | dsviper.InputValue) {
        if (value instanceof dsviper.ValueSet) {
            super(value);
        } else {
            super(new dsviper.ValueSet(mt.type_set_Demo_PlayerKey(), value));
        }
    }

    static wrap(value: dsviper.OutputValue): Set_Demo_PlayerKey {
        return new Set_Demo_PlayerKey(dsviper.ValueSet.cast(value as dsviper.Value));
    }

    get size(): number {
        return this.vprValue.size();
    }

    at(index: number): Demo_PlayerKey {
        return Demo_PlayerKey.wrap(this.vprValue.at(index));
    }

    add(value: Demo_PlayerKey): void {
        this.vprValue.add(value.vprValue);
    }

    discard(value: Demo_PlayerKey): void {
        this.vprValue.discard(value.vprValue);
    }

    remove(value: Demo_PlayerKey): void {
        this.vprValue.remove(value.vprValue);
    }

    pop(): Demo_PlayerKey {
        return Demo_PlayerKey.wrap(this.vprValue.pop());
    }

    contains(value: Demo_PlayerKey): boolean {
        return this.vprValue.index(value.vprValue) !== undefined;
    }

    clear(): void {
        this.vprValue.clear();
    }

    min(): Demo_PlayerKey {
        return Demo_PlayerKey.wrap(this.vprValue.min());
    }

    max(): Demo_PlayerKey {
        return Demo_PlayerKey.wrap(this.vprValue.max());
    }

    union(other: Set_Demo_PlayerKey): Set_Demo_PlayerKey {
        return new Set_Demo_PlayerKey(this.vprValue.union(other.vprValue));
    }

    intersection(other: Set_Demo_PlayerKey): Set_Demo_PlayerKey {
        return new Set_Demo_PlayerKey(this.vprValue.intersection(other.vprValue));
    }

    difference(other: Set_Demo_PlayerKey): Set_Demo_PlayerKey {
        return new Set_Demo_PlayerKey(this.vprValue.difference(other.vprValue));
    }

    symmetricDifference(other: Set_Demo_PlayerKey): Set_Demo_PlayerKey {
        return new Set_Demo_PlayerKey(this.vprValue.symmetricDifference(other.vprValue));
    }

    update(other: Set_Demo_PlayerKey): void {
        this.vprValue.update(other.vprValue);
    }

    intersectionUpdate(other: Set_Demo_PlayerKey): void {
        this.vprValue.intersectionUpdate(other.vprValue);
    }

    differenceUpdate(other: Set_Demo_PlayerKey): void {
        this.vprValue.differenceUpdate(other.vprValue);
    }

    symmetricDifferenceUpdate(other: Set_Demo_PlayerKey): void {
        this.vprValue.symmetricDifferenceUpdate(other.vprValue);
    }

    isdisjoint(other: Set_Demo_PlayerKey): boolean {
        return this.vprValue.isdisjoint(other.vprValue);
    }

    issubset(other: Set_Demo_PlayerKey): boolean {
        return this.vprValue.issubset(other.vprValue);
    }

    issuperset(other: Set_Demo_PlayerKey): boolean {
        return this.vprValue.issuperset(other.vprValue);
    }

    *[Symbol.iterator]() {
        for (const v of this.vprValue) {
            yield Demo_PlayerKey.wrap(v);
        }
    }

    copy(): Set_Demo_PlayerKey {
        return new Set_Demo_PlayerKey(this.vprValue.copy());
    }

    static decode(blob: dsviper.ValueBlob, streamCodecInstancing?: dsviper.StreamCodecInstancing): Set_Demo_PlayerKey {
        const value = dsviper.ValueSet.cast(dsviper.Value.decode(blob, mt.type_set_Demo_PlayerKey(), md.definitions(), streamCodecInstancing ?? dsviper.Codec.STREAM_BINARY));
        return new Set_Demo_PlayerKey(value);
    }
}

