// Generated by kibo from service. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Service.dsm.json by kibo-1.2.10.jar

/**
 * Database getters and setters for attachments defined for service.
 * One exported object per attachment, with short methods (get/set/has/...).
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as md from "./definitions.js";
import * as d from "./data.js";

// Namespace Demo
// attachment<Player, PlayerProperty> Demo::property
export const player_Property = {
    keys(database: dsviper.Database): d.Set_Demo_PlayerKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Demo_Player_Property);
        return new d.Set_Demo_PlayerKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Demo_PlayerKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Demo_Player_Property);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Demo_PlayerKey): d.Optional_Demo_PlayerProperty {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Demo_Player_Property);
        return new d.Optional_Demo_PlayerProperty(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Demo_PlayerKey, value: d.Demo_PlayerProperty): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Demo_Player_Property);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Demo_PlayerKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Demo_Player_Property);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Demo_PlayerKey, d.Demo_PlayerProperty]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};
