// Generated by kibo from service. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Service.dsm.json by kibo-1.2.10.jar

/**
 * Viper Definitions and runtime ids for service.
 */

import dsviper from "@digitalsubstrate/dsviper";
import { B64_DEFINITIONS } from "./resources.js";

let _definitions: dsviper.DefinitionsConst | null = null;

export function definitions(): dsviper.DefinitionsConst {
    if (_definitions === null) {
        const blob = dsviper.ValueBlob.base64Decode(B64_DEFINITIONS);
        const defs = dsviper.Definitions.decode(blob);
        _definitions = defs.const();
    }
    return _definitions;
}

// Concept / club / enum / struct runtime ids
export const RuntimeIds = {
    // Namespace Demo
    Demo_Player: dsviper.ValueUUId.create("c177a251-4de8-57a0-de3b-6cc2ae68eb13"),
    Demo_Level: dsviper.ValueUUId.create("238d8f84-734d-df83-fc48-f4dc69cc127a"),
    Demo_PlayerProperty: dsviper.ValueUUId.create("2fa5978a-9426-26a5-e8e7-35c80ce00ffd"),
    Demo_Vector3: dsviper.ValueUUId.create("9099c892-b971-86b4-6d84-ab38cc2d3d16"),
};

// Attachment runtime ids
export const AttachmentRuntimeIds = {
    // Namespace Demo
    Demo_Player_Property: dsviper.ValueUUId.create("5f39a4c7-fa83-1290-432c-330fc392a39b"),
};