// Generated by kibo from service. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Service.dsm.json by kibo-1.2.10.jar

/**
 * Remote function-pool clients (over ServiceRemote) for service.
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as d from "./data.js";

// Tools
export class Tools {

    private readonly serviceRemote: dsviper.ServiceRemote;

    constructor(serviceRemote: dsviper.ServiceRemote) {
        this.serviceRemote = serviceRemote;
    }

    isAvailable(): boolean {
        return this.serviceRemote.functionPoolFuncs("Tools") !== undefined;
    }

    add(a: bigint, b: bigint): bigint {
        const result = this.serviceRemote.functionPoolFunc("Tools", "add").call(new dsviper.ValueInt64(a), new dsviper.ValueInt64(b)) as unknown as dsviper.OutputValue;
        return result as bigint;
    }
    addVector(a: d.Demo_Vector3, b: d.Demo_Vector3): d.Demo_Vector3 {
        const result = this.serviceRemote.functionPoolFunc("Tools", "add_vector").call(a.vprValue, b.vprValue) as unknown as dsviper.OutputValue;
        return d.Demo_Vector3.wrap(result);
    }
    randomString(size: number): string {
        const result = this.serviceRemote.functionPoolFunc("Tools", "random_string").call(new dsviper.ValueUInt32(size)) as unknown as dsviper.OutputValue;
        return result as string;
    }
}
