// Generated by kibo from service. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Service.dsm.json by kibo-1.2.10.jar

import dsviper from "@digitalsubstrate/dsviper";

export const Path_Root: dsviper.PathConst = new dsviper.Path().const();

// Namespace Demo
export class Demo_Path_PlayerProperty {
    static readonly nickname: dsviper.PathConst = dsviper.Path.fromField("nickname").const();
    static readonly level: dsviper.PathConst = dsviper.Path.fromField("level").const();
}

export class Demo_Path_Vector3 {
    static readonly x: dsviper.PathConst = dsviper.Path.fromField("x").const();
    static readonly y: dsviper.PathConst = dsviper.Path.fromField("y").const();
    static readonly z: dsviper.PathConst = dsviper.Path.fromField("z").const();
}
