// Generated by kibo from service. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Service.dsm.json by kibo-1.2.10.jar

/**
 * Viper types for concepts, clubs, enums, structs and all containers defined for service.
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as md from "./definitions.js";

let _type_void: dsviper.TypeVoid | null = null;
export function type_void(): dsviper.TypeVoid {
    if (_type_void === null) { _type_void = new dsviper.TypeVoid(); }
    return _type_void;
}

// Numbers
let _type_bool: dsviper.TypeBool | null = null;
export function type_bool(): dsviper.TypeBool {
    if (_type_bool === null) { _type_bool = new dsviper.TypeBool(); }
    return _type_bool;
}

let _type_uint8: dsviper.TypeUInt8 | null = null;
export function type_uint8(): dsviper.TypeUInt8 {
    if (_type_uint8 === null) { _type_uint8 = new dsviper.TypeUInt8(); }
    return _type_uint8;
}

let _type_uint16: dsviper.TypeUInt16 | null = null;
export function type_uint16(): dsviper.TypeUInt16 {
    if (_type_uint16 === null) { _type_uint16 = new dsviper.TypeUInt16(); }
    return _type_uint16;
}

let _type_uint32: dsviper.TypeUInt32 | null = null;
export function type_uint32(): dsviper.TypeUInt32 {
    if (_type_uint32 === null) { _type_uint32 = new dsviper.TypeUInt32(); }
    return _type_uint32;
}

let _type_uint64: dsviper.TypeUInt64 | null = null;
export function type_uint64(): dsviper.TypeUInt64 {
    if (_type_uint64 === null) { _type_uint64 = new dsviper.TypeUInt64(); }
    return _type_uint64;
}

let _type_int8: dsviper.TypeInt8 | null = null;
export function type_int8(): dsviper.TypeInt8 {
    if (_type_int8 === null) { _type_int8 = new dsviper.TypeInt8(); }
    return _type_int8;
}

let _type_int16: dsviper.TypeInt16 | null = null;
export function type_int16(): dsviper.TypeInt16 {
    if (_type_int16 === null) { _type_int16 = new dsviper.TypeInt16(); }
    return _type_int16;
}

let _type_int32: dsviper.TypeInt32 | null = null;
export function type_int32(): dsviper.TypeInt32 {
    if (_type_int32 === null) { _type_int32 = new dsviper.TypeInt32(); }
    return _type_int32;
}

let _type_int64: dsviper.TypeInt64 | null = null;
export function type_int64(): dsviper.TypeInt64 {
    if (_type_int64 === null) { _type_int64 = new dsviper.TypeInt64(); }
    return _type_int64;
}

let _type_float: dsviper.TypeFloat | null = null;
export function type_float(): dsviper.TypeFloat {
    if (_type_float === null) { _type_float = new dsviper.TypeFloat(); }
    return _type_float;
}

let _type_double: dsviper.TypeDouble | null = null;
export function type_double(): dsviper.TypeDouble {
    if (_type_double === null) { _type_double = new dsviper.TypeDouble(); }
    return _type_double;
}

// Ids
let _type_blob_id: dsviper.TypeBlobId | null = null;
export function type_blob_id(): dsviper.TypeBlobId {
    if (_type_blob_id === null) { _type_blob_id = new dsviper.TypeBlobId(); }
    return _type_blob_id;
}

let _type_commit_id: dsviper.TypeCommitId | null = null;
export function type_commit_id(): dsviper.TypeCommitId {
    if (_type_commit_id === null) { _type_commit_id = new dsviper.TypeCommitId(); }
    return _type_commit_id;
}

let _type_uuid: dsviper.TypeUUId | null = null;
export function type_uuid(): dsviper.TypeUUId {
    if (_type_uuid === null) { _type_uuid = new dsviper.TypeUUId(); }
    return _type_uuid;
}

// String & Blob
let _type_string: dsviper.TypeString | null = null;
export function type_string(): dsviper.TypeString {
    if (_type_string === null) { _type_string = new dsviper.TypeString(); }
    return _type_string;
}

let _type_blob: dsviper.TypeBlob | null = null;
export function type_blob(): dsviper.TypeBlob {
    if (_type_blob === null) { _type_blob = new dsviper.TypeBlob(); }
    return _type_blob;
}

// Any (runtime singleton)
export function type_any(): dsviper.TypeAny {
    return dsviper.Type.ANY;
}

// AnyConcept (runtime singleton)
export function type_def_any_concept(): dsviper.TypeAnyConcept {
    return dsviper.Type.ANY_CONCEPT;
}

let _type_AnyConceptKey: dsviper.TypeKey | null = null;
export function type_AnyConceptKey(): dsviper.TypeKey {
    if (_type_AnyConceptKey === null) { _type_AnyConceptKey = new dsviper.TypeKey(type_def_any_concept()); }
    return _type_AnyConceptKey;
}

// Vecs

// Mats

// Tuples

// Optionals
let _type_optional_AnyConceptKey: dsviper.TypeOptional | null = null;
export function type_optional_AnyConceptKey(): dsviper.TypeOptional {
    if (_type_optional_AnyConceptKey === null) { _type_optional_AnyConceptKey = new dsviper.TypeOptional(type_AnyConceptKey()); }
    return _type_optional_AnyConceptKey;
}

let _type_optional_Demo_PlayerKey: dsviper.TypeOptional | null = null;
export function type_optional_Demo_PlayerKey(): dsviper.TypeOptional {
    if (_type_optional_Demo_PlayerKey === null) { _type_optional_Demo_PlayerKey = new dsviper.TypeOptional(type_Demo_PlayerKey()); }
    return _type_optional_Demo_PlayerKey;
}

let _type_optional_Demo_PlayerProperty: dsviper.TypeOptional | null = null;
export function type_optional_Demo_PlayerProperty(): dsviper.TypeOptional {
    if (_type_optional_Demo_PlayerProperty === null) { _type_optional_Demo_PlayerProperty = new dsviper.TypeOptional(type_Demo_PlayerProperty()); }
    return _type_optional_Demo_PlayerProperty;
}


// Vectors

// Sets
let _type_set_Demo_PlayerKey: dsviper.TypeSet | null = null;
export function type_set_Demo_PlayerKey(): dsviper.TypeSet {
    if (_type_set_Demo_PlayerKey === null) { _type_set_Demo_PlayerKey = new dsviper.TypeSet(type_Demo_PlayerKey()); }
    return _type_set_Demo_PlayerKey;
}


// Maps

// XArrays

// Variants

// Namespace Demo
let _type_check_Demo_PlayerKey: dsviper.TypeConcept | null = null;
export function type_check_Demo_PlayerKey(): dsviper.TypeConcept {
    if (_type_check_Demo_PlayerKey === null) { _type_check_Demo_PlayerKey = md.definitions().checkConcept(md.RuntimeIds.Demo_Player); }
    return _type_check_Demo_PlayerKey;
}

let _type_Demo_PlayerKey: dsviper.TypeKey | null = null;
export function type_Demo_PlayerKey(): dsviper.TypeKey {
    if (_type_Demo_PlayerKey === null) { _type_Demo_PlayerKey = new dsviper.TypeKey(type_check_Demo_PlayerKey()); }
    return _type_Demo_PlayerKey;
}

let _type_Demo_Level: dsviper.TypeEnumeration | null = null;
export function type_Demo_Level(): dsviper.TypeEnumeration {
    if (_type_Demo_Level === null) { _type_Demo_Level = md.definitions().checkEnumeration(md.RuntimeIds.Demo_Level); }
    return _type_Demo_Level;
}

let _type_Demo_PlayerProperty: dsviper.TypeStructure | null = null;
export function type_Demo_PlayerProperty(): dsviper.TypeStructure {
    if (_type_Demo_PlayerProperty === null) { _type_Demo_PlayerProperty = md.definitions().checkStructure(md.RuntimeIds.Demo_PlayerProperty); }
    return _type_Demo_PlayerProperty;
}

let _type_Demo_Vector3: dsviper.TypeStructure | null = null;
export function type_Demo_Vector3(): dsviper.TypeStructure {
    if (_type_Demo_Vector3 === null) { _type_Demo_Vector3 = md.definitions().checkStructure(md.RuntimeIds.Demo_Vector3); }
    return _type_Demo_Vector3;
}

let _attachment_Demo_Player_Property: dsviper.Attachment | null = null;
export function attachment_Demo_Player_Property(): dsviper.Attachment {
    if (_attachment_Demo_Player_Property === null) { _attachment_Demo_Player_Property = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Demo_Player_Property); }
    return _attachment_Demo_Player_Property;
}
