[project]
definitions = "definitions/Service"
infrastructure = "service"

[generator]
templates = "2"
manifests = ["../templates/features.json"]

[target.cpp]
features = ["Pool", "PoolRemote", "Test"]
output = "cpp/generated"
clean = true

[target.python]
features = ["Base", "Pool", "Wheel"]
output = "python/generated"

[target.typescript]
features = ["Base", "Pool", "Package"]
output = "typescript/generated"
