// Generated by kibo from features. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Features.dsm.json by kibo-1.2.10.jar

/**
 * Getters and setters for attachments defined for features.
 * One exported object per attachment, with short methods (get/set/has/...).
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as mp from "./path.js";
import * as mt from "./value_type.js";
import * as d from "./data.js";

// Namespace Test
// attachment<any_concept, any> Test::propertiesAnyConceptAny
export const any_concept_PropertiesAnyConceptAny = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_AnyConceptKey {
        const attachment = mt.attachment_Test_Any_concept_PropertiesAnyConceptAny();
        return new d.Set_AnyConceptKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_AnyConceptKey, d.Set_AnyConceptKey, d.Set_AnyConceptKey, d.Set_AnyConceptKey] {
        const attachment = mt.attachment_Test_Any_concept_PropertiesAnyConceptAny();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_AnyConceptKey(added), new d.Set_AnyConceptKey(removed), new d.Set_AnyConceptKey(different), new d.Set_AnyConceptKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.AnyConceptKey): boolean {
        const attachment = mt.attachment_Test_Any_concept_PropertiesAnyConceptAny();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.AnyConceptKey): d.Optional_Any {
        const attachment = mt.attachment_Test_Any_concept_PropertiesAnyConceptAny();
        return new d.Optional_Any(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.AnyConceptKey, value: dsviper.ValueAny): void {
        const attachment = mt.attachment_Test_Any_concept_PropertiesAnyConceptAny();
        attachmentMutating.set(attachment, key.vprValue, value);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.AnyConceptKey, value: dsviper.ValueAny, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_Any_concept_PropertiesAnyConceptAny();
        attachmentMutating.diff(attachment, key.vprValue, value, recursive);
    },


    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.AnyConceptKey, dsviper.ValueAny]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, StructureV> Test::properties
export const conceptA_Properties = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Test_ConceptAKey {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        return new d.Set_Test_ConceptAKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey] {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Test_ConceptAKey(added), new d.Set_Test_ConceptAKey(removed), new d.Set_Test_ConceptAKey(different), new d.Set_Test_ConceptAKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): boolean {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): d.Optional_Test_StructureV {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        return new d.Optional_Test_StructureV(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Test_StructureV): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.set(attachment, key.vprValue, value.vprValue);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Test_StructureV, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.diff(attachment, key.vprValue, value.vprValue, recursive);
    },

    setF_bool(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: boolean): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_bool, value);
    },

    setF_uint8(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uint8, value);
    },

    setF_uint16(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uint16, value);
    },

    setF_uint32(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uint32, value);
    },

    setF_uint64(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: bigint): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uint64, value);
    },

    setF_int8(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_int8, value);
    },

    setF_int16(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_int16, value);
    },

    setF_int32(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_int32, value);
    },

    setF_int64(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: bigint): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_int64, value);
    },

    setF_float(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_float, value);
    },

    setF_double(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_double, value);
    },

    setF_uuid(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: dsviper.ValueUUId): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uuid, value);
    },

    setF_string(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: string): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_string, value);
    },

    setF_vec(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Vec_uint8_2): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_vec, value.vprValue);
    },

    setF_mat(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Mat_uint8_2_3): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_mat, value.vprValue);
    },

    setF_tuple(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Tuple_uint8_string): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_tuple, value.vprValue);
    },

    setF_optional(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Optional_uint8): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_optional, value.vprValue);
    },

    setF_vector(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Vector_uint8): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_vector, value.vprValue);
    },

    setF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_set, value.vprValue);
    },
    unionF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.unionInSet(attachment, key.vprValue, mp.Test_Path_StructureV.f_set, value.vprValue);
    },
    subtractF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.subtractInSet(attachment, key.vprValue, mp.Test_Path_StructureV.f_set, value.vprValue);
    },
    setF_map(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Map_uint8_to_string): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_map, value.vprValue);
    },
    unionF_map(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Map_uint8_to_string): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.unionInMap(attachment, key.vprValue, mp.Test_Path_StructureV.f_map, value.vprValue);
    },
    subtractF_map(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.subtractInMap(attachment, key.vprValue, mp.Test_Path_StructureV.f_map, value.vprValue);
    },
    updateF_map(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Map_uint8_to_string): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.updateInMap(attachment, key.vprValue, mp.Test_Path_StructureV.f_map, value.vprValue);
    },
    setF_E(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Test_EnumerationE): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_E, value.vprValue);
    },

    setF_S(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_S, value.vprValue);
    },

    setF_T(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Test_StructureT): void {
        const attachment = mt.attachment_Test_ConceptA_Properties();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_T, value.vprValue);
    },


    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Test_ConceptAKey, d.Test_StructureV]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, int8> Test::propertiesInt8
export const conceptA_PropertiesInt8 = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Test_ConceptAKey {
        const attachment = mt.attachment_Test_ConceptA_PropertiesInt8();
        return new d.Set_Test_ConceptAKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey] {
        const attachment = mt.attachment_Test_ConceptA_PropertiesInt8();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Test_ConceptAKey(added), new d.Set_Test_ConceptAKey(removed), new d.Set_Test_ConceptAKey(different), new d.Set_Test_ConceptAKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): boolean {
        const attachment = mt.attachment_Test_ConceptA_PropertiesInt8();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): d.Optional_int8 {
        const attachment = mt.attachment_Test_ConceptA_PropertiesInt8();
        return new d.Optional_int8(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesInt8();
        attachmentMutating.set(attachment, key.vprValue, value);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: number, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesInt8();
        attachmentMutating.diff(attachment, key.vprValue, value, recursive);
    },


    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Test_ConceptAKey, number]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, map<int8, string>> Test::propertiesMapInt8String
export const conceptA_PropertiesMapInt8String = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Test_ConceptAKey {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        return new d.Set_Test_ConceptAKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey] {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Test_ConceptAKey(added), new d.Set_Test_ConceptAKey(removed), new d.Set_Test_ConceptAKey(different), new d.Set_Test_ConceptAKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): boolean {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): d.Optional_Map_int8_to_string {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        return new d.Optional_Map_int8_to_string(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Map_int8_to_string): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        attachmentMutating.set(attachment, key.vprValue, value.vprValue);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Map_int8_to_string, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        attachmentMutating.diff(attachment, key.vprValue, value.vprValue, recursive);
    },

    union(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Map_int8_to_string): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        attachmentMutating.unionInMap(attachment, key.vprValue, mp.Path_Root, value.vprValue);
    },
    subtract(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Set_int8): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        attachmentMutating.subtractInMap(attachment, key.vprValue, mp.Path_Root, value.vprValue);
    },
    update(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Map_int8_to_string): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesMapInt8String();
        attachmentMutating.updateInMap(attachment, key.vprValue, mp.Path_Root, value.vprValue);
    },

    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Test_ConceptAKey, d.Map_int8_to_string]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, set<int8>> Test::propertiesSeInt8
export const conceptA_PropertiesSeInt8 = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Test_ConceptAKey {
        const attachment = mt.attachment_Test_ConceptA_PropertiesSeInt8();
        return new d.Set_Test_ConceptAKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey] {
        const attachment = mt.attachment_Test_ConceptA_PropertiesSeInt8();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Test_ConceptAKey(added), new d.Set_Test_ConceptAKey(removed), new d.Set_Test_ConceptAKey(different), new d.Set_Test_ConceptAKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): boolean {
        const attachment = mt.attachment_Test_ConceptA_PropertiesSeInt8();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): d.Optional_Set_int8 {
        const attachment = mt.attachment_Test_ConceptA_PropertiesSeInt8();
        return new d.Optional_Set_int8(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Set_int8): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesSeInt8();
        attachmentMutating.set(attachment, key.vprValue, value.vprValue);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Set_int8, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesSeInt8();
        attachmentMutating.diff(attachment, key.vprValue, value.vprValue, recursive);
    },

    union(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Optional_Set_int8): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesSeInt8();
        attachmentMutating.unionInSet(attachment, key.vprValue, mp.Path_Root, value.vprValue);
    },
    subtract(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.Set_int8): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesSeInt8();
        attachmentMutating.subtractInSet(attachment, key.vprValue, mp.Path_Root, value.vprValue);
    },

    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Test_ConceptAKey, d.Set_int8]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, xarray<int8>> Test::propertiesXArray
export const conceptA_PropertiesXArray = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Test_ConceptAKey {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        return new d.Set_Test_ConceptAKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey, d.Set_Test_ConceptAKey] {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Test_ConceptAKey(added), new d.Set_Test_ConceptAKey(removed), new d.Set_Test_ConceptAKey(different), new d.Set_Test_ConceptAKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): boolean {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptAKey): d.Optional_XArray_int8 {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        return new d.Optional_XArray_int8(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.XArray_int8): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        attachmentMutating.set(attachment, key.vprValue, value.vprValue);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, value: d.XArray_int8, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        attachmentMutating.diff(attachment, key.vprValue, value.vprValue, recursive);
    },

    insert(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, beforePosition: dsviper.ValueUUId, newPosition: dsviper.ValueUUId, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        attachmentMutating.insertInXarray(attachment, key.vprValue, mp.Path_Root, beforePosition, newPosition, value);
    },
    update(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, position: dsviper.ValueUUId, value: number): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        attachmentMutating.updateInXarray(attachment, key.vprValue, mp.Path_Root, position, value);
    },
    remove(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptAKey, position: dsviper.ValueUUId): void {
        const attachment = mt.attachment_Test_ConceptA_PropertiesXArray();
        attachmentMutating.removeInXarray(attachment, key.vprValue, mp.Path_Root, position);
    },

    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Test_ConceptAKey, d.XArray_int8]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptB, StructureT> Test::propertiesB
export const conceptB_PropertiesB = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Test_ConceptBKey {
        const attachment = mt.attachment_Test_ConceptB_PropertiesB();
        return new d.Set_Test_ConceptBKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Test_ConceptBKey, d.Set_Test_ConceptBKey, d.Set_Test_ConceptBKey, d.Set_Test_ConceptBKey] {
        const attachment = mt.attachment_Test_ConceptB_PropertiesB();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Test_ConceptBKey(added), new d.Set_Test_ConceptBKey(removed), new d.Set_Test_ConceptBKey(different), new d.Set_Test_ConceptBKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptBKey): boolean {
        const attachment = mt.attachment_Test_ConceptB_PropertiesB();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptBKey): d.Optional_Test_StructureT {
        const attachment = mt.attachment_Test_ConceptB_PropertiesB();
        return new d.Optional_Test_StructureT(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptBKey, value: d.Test_StructureT): void {
        const attachment = mt.attachment_Test_ConceptB_PropertiesB();
        attachmentMutating.set(attachment, key.vprValue, value.vprValue);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptBKey, value: d.Test_StructureT, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_ConceptB_PropertiesB();
        attachmentMutating.diff(attachment, key.vprValue, value.vprValue, recursive);
    },

    setField_string(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptBKey, value: string): void {
        const attachment = mt.attachment_Test_ConceptB_PropertiesB();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureT.field_string, value);
    },

    setField_structure_s(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptBKey, value: d.Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptB_PropertiesB();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureT.field_structure_s, value.vprValue);
    },


    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Test_ConceptBKey, d.Test_StructureT]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptC, StructureU> Test::propertiesC
export const conceptC_PropertiesC = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Test_ConceptCKey {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        return new d.Set_Test_ConceptCKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Test_ConceptCKey, d.Set_Test_ConceptCKey, d.Set_Test_ConceptCKey, d.Set_Test_ConceptCKey] {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Test_ConceptCKey(added), new d.Set_Test_ConceptCKey(removed), new d.Set_Test_ConceptCKey(different), new d.Set_Test_ConceptCKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptCKey): boolean {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_ConceptCKey): d.Optional_Test_StructureU {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        return new d.Optional_Test_StructureU(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_StructureU): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.set(attachment, key.vprValue, value.vprValue);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_StructureU, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.diff(attachment, key.vprValue, value.vprValue, recursive);
    },

    setF_bool(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: boolean): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_bool, value);
    },

    setF_uint8(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_uint8, value);
    },

    setF_uint16(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_uint16, value);
    },

    setF_uint32(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_uint32, value);
    },

    setF_uint64(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: bigint): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_uint64, value);
    },

    setF_int8(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_int8, value);
    },

    setF_int16(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_int16, value);
    },

    setF_int32(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_int32, value);
    },

    setF_int64(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: bigint): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_int64, value);
    },

    setF_float(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_float, value);
    },

    setF_double(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_double, value);
    },

    setF_blob_id(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: dsviper.ValueBlobId): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_blob_id, value);
    },

    setF_commit_id(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: dsviper.ValueCommitId): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_commit_id, value);
    },

    setF_uuid(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: dsviper.ValueUUId): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_uuid, value);
    },

    setF_string(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_string, value);
    },

    setF_blob(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: dsviper.ValueBlob): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_blob, value);
    },

    setF_vec(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Vec_uint8_2): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_vec, value.vprValue);
    },

    setF_mat(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Mat_uint8_2_2): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_mat, value.vprValue);
    },

    setF_tuple(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Tuple_uint8_string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_tuple, value.vprValue);
    },

    setF_optional(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Optional_uint8): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_optional, value.vprValue);
    },

    setF_vector(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Vector_uint8): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_vector, value.vprValue);
    },

    setF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_set, value.vprValue);
    },
    unionF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.unionInSet(attachment, key.vprValue, mp.Test_Path_StructureU.f_set, value.vprValue);
    },
    subtractF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.subtractInSet(attachment, key.vprValue, mp.Test_Path_StructureU.f_set, value.vprValue);
    },
    setF_set_s(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_set_s, value.vprValue);
    },
    unionF_set_s(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.unionInSet(attachment, key.vprValue, mp.Test_Path_StructureU.f_set_s, value.vprValue);
    },
    subtractF_set_s(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.subtractInSet(attachment, key.vprValue, mp.Test_Path_StructureU.f_set_s, value.vprValue);
    },
    setF_map_s1(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_Test_StructureS_to_string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_s1, value.vprValue);
    },
    unionF_map_s1(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_Test_StructureS_to_string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.unionInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_s1, value.vprValue);
    },
    subtractF_map_s1(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.subtractInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_s1, value.vprValue);
    },
    updateF_map_s1(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_Test_StructureS_to_string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.updateInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_s1, value.vprValue);
    },
    setF_map_s2(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_string_to_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_s2, value.vprValue);
    },
    unionF_map_s2(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_string_to_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.unionInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_s2, value.vprValue);
    },
    subtractF_map_s2(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.subtractInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_s2, value.vprValue);
    },
    updateF_map_s2(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_string_to_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.updateInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_s2, value.vprValue);
    },
    setF_xarray(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.XArray_uint8): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_xarray, value.vprValue);
    },
    insertF_xarray(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, beforePosition: dsviper.ValueUUId, newPosition: dsviper.ValueUUId, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.insertInXarray(attachment, key.vprValue, mp.Test_Path_StructureU.f_xarray, beforePosition, newPosition, value);
    },
    updateF_xarray(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, position: dsviper.ValueUUId, value: number): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.updateInXarray(attachment, key.vprValue, mp.Test_Path_StructureU.f_xarray, position, value);
    },
    removeF_xarray(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, position: dsviper.ValueUUId): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.removeInXarray(attachment, key.vprValue, mp.Test_Path_StructureU.f_xarray, position);
    },
    setF_map_vs(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_Vector_Test_StructureS_to_string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_vs, value.vprValue);
    },
    unionF_map_vs(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_Vector_Test_StructureS_to_string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.unionInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_vs, value.vprValue);
    },
    subtractF_map_vs(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Set_Vector_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.subtractInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_vs, value.vprValue);
    },
    updateF_map_vs(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Map_Vector_Test_StructureS_to_string): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.updateInMap(attachment, key.vprValue, mp.Test_Path_StructureU.f_map_vs, value.vprValue);
    },
    setF_variant(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Variant_string_uint8_Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_variant, value.vprValue);
    },

    setF_any(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: dsviper.ValueAny): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_any, value);
    },

    setF_E(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_EnumerationE): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_E, value.vprValue);
    },

    setF_S(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_StructureS): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_S, value.vprValue);
    },

    setF_T(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_StructureT): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_T, value.vprValue);
    },

    setF_A(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_ConceptAKey): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_A, value.vprValue);
    },

    setF_B(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_ConceptBKey): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_B, value.vprValue);
    },

    setF_C(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_ConceptCKey): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_C, value.vprValue);
    },

    setF_D(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_ConceptDKey): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_D, value.vprValue);
    },

    setF_Klub(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.Test_KlubKey): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_Klub, value.vprValue);
    },

    setF_any_concept(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_ConceptCKey, value: d.AnyConceptKey): void {
        const attachment = mt.attachment_Test_ConceptC_PropertiesC();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureU.f_any_concept, value.vprValue);
    },


    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Test_ConceptCKey, d.Test_StructureU]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<Klub, StructureV> Test::propertiesD
export const klub_PropertiesD = {
    keys(attachmentGetting: dsviper.AttachmentGetting): d.Set_Test_KlubKey {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        return new d.Set_Test_KlubKey(attachmentGetting.keys(attachment));
    },

    diffKeys(current: dsviper.AttachmentGetting, other: dsviper.AttachmentGetting): [d.Set_Test_KlubKey, d.Set_Test_KlubKey, d.Set_Test_KlubKey, d.Set_Test_KlubKey] {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        const [added, removed, different, same] = dsviper.AttachmentGetting.diffKeys(current, other, attachment);
        return [new d.Set_Test_KlubKey(added), new d.Set_Test_KlubKey(removed), new d.Set_Test_KlubKey(different), new d.Set_Test_KlubKey(same)];
    },

    has(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_KlubKey): boolean {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        return attachmentGetting.has(attachment, key.vprValue);
    },

    get(attachmentGetting: dsviper.AttachmentGetting, key: d.Test_KlubKey): d.Optional_Test_StructureV {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        return new d.Optional_Test_StructureV(attachmentGetting.get(attachment, key.vprValue));
    },

    set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Test_StructureV): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.set(attachment, key.vprValue, value.vprValue);
    },

    diff(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Test_StructureV, recursive: boolean = false): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.diff(attachment, key.vprValue, value.vprValue, recursive);
    },

    setF_bool(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: boolean): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_bool, value);
    },

    setF_uint8(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: number): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uint8, value);
    },

    setF_uint16(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: number): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uint16, value);
    },

    setF_uint32(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: number): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uint32, value);
    },

    setF_uint64(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: bigint): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uint64, value);
    },

    setF_int8(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: number): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_int8, value);
    },

    setF_int16(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: number): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_int16, value);
    },

    setF_int32(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: number): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_int32, value);
    },

    setF_int64(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: bigint): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_int64, value);
    },

    setF_float(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: number): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_float, value);
    },

    setF_double(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: number): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_double, value);
    },

    setF_uuid(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: dsviper.ValueUUId): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_uuid, value);
    },

    setF_string(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: string): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_string, value);
    },

    setF_vec(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Vec_uint8_2): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_vec, value.vprValue);
    },

    setF_mat(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Mat_uint8_2_3): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_mat, value.vprValue);
    },

    setF_tuple(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Tuple_uint8_string): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_tuple, value.vprValue);
    },

    setF_optional(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Optional_uint8): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_optional, value.vprValue);
    },

    setF_vector(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Vector_uint8): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_vector, value.vprValue);
    },

    setF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_set, value.vprValue);
    },
    unionF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.unionInSet(attachment, key.vprValue, mp.Test_Path_StructureV.f_set, value.vprValue);
    },
    subtractF_set(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.subtractInSet(attachment, key.vprValue, mp.Test_Path_StructureV.f_set, value.vprValue);
    },
    setF_map(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Map_uint8_to_string): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_map, value.vprValue);
    },
    unionF_map(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Map_uint8_to_string): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.unionInMap(attachment, key.vprValue, mp.Test_Path_StructureV.f_map, value.vprValue);
    },
    subtractF_map(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Set_uint8): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.subtractInMap(attachment, key.vprValue, mp.Test_Path_StructureV.f_map, value.vprValue);
    },
    updateF_map(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Map_uint8_to_string): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.updateInMap(attachment, key.vprValue, mp.Test_Path_StructureV.f_map, value.vprValue);
    },
    setF_E(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Test_EnumerationE): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_E, value.vprValue);
    },

    setF_S(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Test_StructureS): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_S, value.vprValue);
    },

    setF_T(attachmentMutating: dsviper.AttachmentMutating, key: d.Test_KlubKey, value: d.Test_StructureT): void {
        const attachment = mt.attachment_Test_Klub_PropertiesD();
        attachmentMutating.update(attachment, key.vprValue, mp.Test_Path_StructureV.f_T, value.vprValue);
    },


    *enumerate(attachmentGetting: dsviper.AttachmentGetting): Generator<[d.Test_KlubKey, d.Test_StructureV]> {
        for (const key of this.keys(attachmentGetting)) {
            const document = this.get(attachmentGetting, key).unwrap();
            yield [key, document];
        }
    },
};
