// Generated by kibo from features. Do not edit by hand.
// Templates: kibo-template-viper 1.2.1 (MIT).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Features.dsm.json by kibo-1.2.11.jar

/**
 * Remote attachment function-pool clients (over ServiceRemote) for features.
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as d from "./data.js";

