// Generated by kibo from features. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Features.dsm.json by kibo-1.2.10.jar

/**
 * Database getters and setters for attachments defined for features.
 * One exported object per attachment, with short methods (get/set/has/...).
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as md from "./definitions.js";
import * as d from "./data.js";

// Namespace Test
// attachment<any_concept, any> Test::propertiesAnyConceptAny
export const any_concept_PropertiesAnyConceptAny = {
    keys(database: dsviper.Database): d.Set_AnyConceptKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        return new d.Set_AnyConceptKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.AnyConceptKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.AnyConceptKey): d.Optional_Any {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        return new d.Optional_Any(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.AnyConceptKey, value: dsviper.ValueAny): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.AnyConceptKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.AnyConceptKey, dsviper.ValueAny]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, StructureV> Test::properties
export const conceptA_Properties = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_Test_StructureV {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        return new d.Optional_Test_StructureV(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: d.Test_StructureV): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, d.Test_StructureV]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, int8> Test::propertiesInt8
export const conceptA_PropertiesInt8 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_int8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        return new d.Optional_int8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, map<int8, string>> Test::propertiesMapInt8String
export const conceptA_PropertiesMapInt8String = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_Map_int8_to_string {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        return new d.Optional_Map_int8_to_string(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: d.Map_int8_to_string): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, d.Map_int8_to_string]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, set<int8>> Test::propertiesSeInt8
export const conceptA_PropertiesSeInt8 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_Set_int8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        return new d.Optional_Set_int8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: d.Set_int8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, d.Set_int8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, xarray<int8>> Test::propertiesXArray
export const conceptA_PropertiesXArray = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_XArray_int8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        return new d.Optional_XArray_int8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: d.XArray_int8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, d.XArray_int8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptB, StructureT> Test::propertiesB
export const conceptB_PropertiesB = {
    keys(database: dsviper.Database): d.Set_Test_ConceptBKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        return new d.Set_Test_ConceptBKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptBKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptBKey): d.Optional_Test_StructureT {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        return new d.Optional_Test_StructureT(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptBKey, value: d.Test_StructureT): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptBKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptBKey, d.Test_StructureT]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptC, StructureU> Test::propertiesC
export const conceptC_PropertiesC = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        return new d.Set_Test_ConceptCKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCKey): d.Optional_Test_StructureU {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        return new d.Optional_Test_StructureU(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCKey, value: d.Test_StructureU): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCKey, d.Test_StructureU]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<Klub, StructureV> Test::propertiesD
export const klub_PropertiesD = {
    keys(database: dsviper.Database): d.Set_Test_KlubKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        return new d.Set_Test_KlubKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_KlubKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_KlubKey): d.Optional_Test_StructureV {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        return new d.Optional_Test_StructureV(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_KlubKey, value: d.Test_StructureV): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_KlubKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_KlubKey, d.Test_StructureV]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};
