// Generated by kibo from features. Do not edit by hand.
// Templates: kibo-template-viper 1.2.1 (MIT).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Features.dsm.json by kibo-1.2.11.jar

/**
 * Database getters and setters for attachments defined for features.
 * One exported object per attachment, with short methods (get/set/has/...).
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as md from "./definitions.js";
import * as d from "./data.js";

// Namespace Test
// attachment<any_concept, any> Test::propertiesAnyConceptAny
export const any_concept_PropertiesAnyConceptAny = {
    keys(database: dsviper.Database): d.Set_AnyConceptKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        return new d.Set_AnyConceptKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.AnyConceptKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.AnyConceptKey): d.Optional_Any {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        return new d.Optional_Any(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.AnyConceptKey, value: dsviper.ValueAny): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.AnyConceptKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.AnyConceptKey, dsviper.ValueAny]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, StructureV> Test::properties
export const conceptA_Properties = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_Test_StructureV {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        return new d.Optional_Test_StructureV(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: d.Test_StructureV): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, d.Test_StructureV]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, int8> Test::propertiesInt8
export const conceptA_PropertiesInt8 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_int8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        return new d.Optional_int8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, map<int8, string>> Test::propertiesMapInt8String
export const conceptA_PropertiesMapInt8String = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_Map_int8_to_string {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        return new d.Optional_Map_int8_to_string(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: d.Map_int8_to_string): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, d.Map_int8_to_string]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, set<int8>> Test::propertiesSeInt8
export const conceptA_PropertiesSeInt8 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_Set_int8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        return new d.Optional_Set_int8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: d.Set_int8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, d.Set_int8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptA, xarray<int8>> Test::propertiesXArray
export const conceptA_PropertiesXArray = {
    keys(database: dsviper.Database): d.Set_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        return new d.Set_Test_ConceptAKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptAKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptAKey): d.Optional_XArray_int8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        return new d.Optional_XArray_int8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptAKey, value: d.XArray_int8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptAKey, d.XArray_int8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptB, StructureT> Test::propertiesB
export const conceptB_PropertiesB = {
    keys(database: dsviper.Database): d.Set_Test_ConceptBKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        return new d.Set_Test_ConceptBKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptBKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptBKey): d.Optional_Test_StructureT {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        return new d.Optional_Test_StructureT(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptBKey, value: d.Test_StructureT): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptBKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptBKey, d.Test_StructureT]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptC, StructureU> Test::propertiesC
export const conceptC_PropertiesC = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        return new d.Set_Test_ConceptCKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCKey): d.Optional_Test_StructureU {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        return new d.Optional_Test_StructureU(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCKey, value: d.Test_StructureU): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCKey, d.Test_StructureU]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, any> Test::docAny
export const conceptCoverage_DocAny = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAny);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAny);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Any {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAny);
        return new d.Optional_Any(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: dsviper.ValueAny): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAny);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAny);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, dsviper.ValueAny]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, key<any_concept>> Test::docAnyConceptKey
export const conceptCoverage_DocAnyConceptKey = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAnyConceptKey);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAnyConceptKey);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_AnyConceptKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAnyConceptKey);
        return new d.Optional_AnyConceptKey(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.AnyConceptKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAnyConceptKey);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAnyConceptKey);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.AnyConceptKey]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, blob> Test::docBlob
export const conceptCoverage_DocBlob = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlob);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlob);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_blob {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlob);
        return new d.Optional_blob(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: dsviper.ValueBlob): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlob);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlob);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, dsviper.ValueBlob]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, blob_id> Test::docBlobId
export const conceptCoverage_DocBlobId = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlobId);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlobId);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_blob_id {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlobId);
        return new d.Optional_blob_id(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: dsviper.ValueBlobId): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlobId);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlobId);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, dsviper.ValueBlobId]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, bool> Test::docBool
export const conceptCoverage_DocBool = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBool);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBool);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_bool {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBool);
        return new d.Optional_bool(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: boolean): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBool);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBool);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, boolean]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, key<Klub>> Test::docClubKey
export const conceptCoverage_DocClubKey = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocClubKey);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocClubKey);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Test_KlubKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocClubKey);
        return new d.Optional_Test_KlubKey(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Test_KlubKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocClubKey);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocClubKey);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Test_KlubKey]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, commit_id> Test::docCommitId
export const conceptCoverage_DocCommitId = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocCommitId);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocCommitId);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_commit_id {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocCommitId);
        return new d.Optional_commit_id(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: dsviper.ValueCommitId): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocCommitId);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocCommitId);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, dsviper.ValueCommitId]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, key<ConceptA>> Test::docConceptKey
export const conceptCoverage_DocConceptKey = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocConceptKey);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocConceptKey);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Test_ConceptAKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocConceptKey);
        return new d.Optional_Test_ConceptAKey(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Test_ConceptAKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocConceptKey);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocConceptKey);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Test_ConceptAKey]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, double> Test::docDouble
export const conceptCoverage_DocDouble = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocDouble);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocDouble);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_double {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocDouble);
        return new d.Optional_double(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocDouble);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocDouble);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, EnumerationE> Test::docEnumeration
export const conceptCoverage_DocEnumeration = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocEnumeration);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocEnumeration);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Test_EnumerationE {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocEnumeration);
        return new d.Optional_Test_EnumerationE(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Test_EnumerationE): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocEnumeration);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocEnumeration);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Test_EnumerationE]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, float> Test::docFloat
export const conceptCoverage_DocFloat = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocFloat);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocFloat);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_float {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocFloat);
        return new d.Optional_float(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocFloat);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocFloat);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, int16> Test::docInt16
export const conceptCoverage_DocInt16 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt16);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt16);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_int16 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt16);
        return new d.Optional_int16(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt16);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt16);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, int32> Test::docInt32
export const conceptCoverage_DocInt32 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt32);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt32);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_int32 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt32);
        return new d.Optional_int32(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt32);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt32);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, int64> Test::docInt64
export const conceptCoverage_DocInt64 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt64);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt64);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_int64 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt64);
        return new d.Optional_int64(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: bigint): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt64);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt64);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, bigint]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, int8> Test::docInt8
export const conceptCoverage_DocInt8 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt8);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt8);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_int8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt8);
        return new d.Optional_int8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt8);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt8);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, map<uint8, string>> Test::docMap
export const conceptCoverage_DocMap = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMap);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMap);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Map_uint8_to_string {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMap);
        return new d.Optional_Map_uint8_to_string(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Map_uint8_to_string): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMap);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMap);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Map_uint8_to_string]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, mat<uint8, 2, 2>> Test::docMat
export const conceptCoverage_DocMat = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMat);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMat);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Mat_uint8_2_2 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMat);
        return new d.Optional_Mat_uint8_2_2(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Mat_uint8_2_2): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMat);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMat);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Mat_uint8_2_2]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, optional<uint8>> Test::docOptional
export const conceptCoverage_DocOptional = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocOptional);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocOptional);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Optional_uint8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocOptional);
        return new d.Optional_Optional_uint8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Optional_uint8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocOptional);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocOptional);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Optional_uint8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, set<uint8>> Test::docSet
export const conceptCoverage_DocSet = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocSet);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocSet);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Set_uint8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocSet);
        return new d.Optional_Set_uint8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Set_uint8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocSet);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocSet);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Set_uint8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, string> Test::docString
export const conceptCoverage_DocString = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocString);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocString);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_string {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocString);
        return new d.Optional_string(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: string): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocString);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocString);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, string]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, StructureW> Test::docStructureSingleField
export const conceptCoverage_DocStructureSingleField = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocStructureSingleField);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocStructureSingleField);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Test_StructureW {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocStructureSingleField);
        return new d.Optional_Test_StructureW(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Test_StructureW): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocStructureSingleField);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocStructureSingleField);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Test_StructureW]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, tuple<uint8, string>> Test::docTuple
export const conceptCoverage_DocTuple = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocTuple);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocTuple);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Tuple_uint8_string {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocTuple);
        return new d.Optional_Tuple_uint8_string(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Tuple_uint8_string): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocTuple);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocTuple);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Tuple_uint8_string]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, uint16> Test::docUInt16
export const conceptCoverage_DocUInt16 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt16);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt16);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_uint16 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt16);
        return new d.Optional_uint16(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt16);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt16);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, uint32> Test::docUInt32
export const conceptCoverage_DocUInt32 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt32);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt32);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_uint32 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt32);
        return new d.Optional_uint32(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt32);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt32);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, uint64> Test::docUInt64
export const conceptCoverage_DocUInt64 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt64);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt64);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_uint64 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt64);
        return new d.Optional_uint64(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: bigint): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt64);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt64);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, bigint]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, uint8> Test::docUInt8
export const conceptCoverage_DocUInt8 = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt8);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt8);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_uint8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt8);
        return new d.Optional_uint8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: number): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt8);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt8);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, number]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, uuid> Test::docUUId
export const conceptCoverage_DocUUId = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUUId);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUUId);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_uuid {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUUId);
        return new d.Optional_uuid(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: dsviper.ValueUUId): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUUId);
        database.set(attachment, key.vprValue, value);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUUId);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, dsviper.ValueUUId]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, variant<string, uint8>> Test::docVariant
export const conceptCoverage_DocVariant = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVariant);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVariant);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Variant_string_uint8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVariant);
        return new d.Optional_Variant_string_uint8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Variant_string_uint8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVariant);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVariant);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Variant_string_uint8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, vec<uint8, 2>> Test::docVec
export const conceptCoverage_DocVec = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVec);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVec);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Vec_uint8_2 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVec);
        return new d.Optional_Vec_uint8_2(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Vec_uint8_2): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVec);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVec);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Vec_uint8_2]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, vector<uint8>> Test::docVector
export const conceptCoverage_DocVector = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVector);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVector);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_Vector_uint8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVector);
        return new d.Optional_Vector_uint8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.Vector_uint8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVector);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVector);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.Vector_uint8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<ConceptCoverage, xarray<uint8>> Test::docXArray
export const conceptCoverage_DocXArray = {
    keys(database: dsviper.Database): d.Set_Test_ConceptCoverageKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocXArray);
        return new d.Set_Test_ConceptCoverageKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_ConceptCoverageKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocXArray);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_ConceptCoverageKey): d.Optional_XArray_uint8 {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocXArray);
        return new d.Optional_XArray_uint8(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_ConceptCoverageKey, value: d.XArray_uint8): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocXArray);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_ConceptCoverageKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocXArray);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_ConceptCoverageKey, d.XArray_uint8]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};

// attachment<Klub, StructureV> Test::propertiesD
export const klub_PropertiesD = {
    keys(database: dsviper.Database): d.Set_Test_KlubKey {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        return new d.Set_Test_KlubKey(database.keys(attachment));
    },

    has(database: dsviper.Database, key: d.Test_KlubKey): boolean {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        return database.has(attachment, key.vprValue);
    },

    get(database: dsviper.Database, key: d.Test_KlubKey): d.Optional_Test_StructureV {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        return new d.Optional_Test_StructureV(database.get(attachment, key.vprValue));
    },

    set(database: dsviper.Database, key: d.Test_KlubKey, value: d.Test_StructureV): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        database.set(attachment, key.vprValue, value.vprValue);
    },

    del(database: dsviper.Database, key: d.Test_KlubKey): void {
        const attachment = database.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD);
        database.delete(attachment, key.vprValue);
    },

    *enumerate(database: dsviper.Database): Generator<[d.Test_KlubKey, d.Test_StructureV]> {
        for (const key of this.keys(database)) {
            const document = this.get(database, key).unwrap();
            yield [key, document];
        }
    },
};
