// Generated by kibo from features. Do not edit by hand.
// Templates: MIT (kibo-template-viper).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Features.dsm.json by kibo-1.2.10.jar

/**
 * Viper Definitions and runtime ids for features.
 */

import dsviper from "@digitalsubstrate/dsviper";
import { B64_DEFINITIONS } from "./resources.js";

let _definitions: dsviper.DefinitionsConst | null = null;

export function definitions(): dsviper.DefinitionsConst {
    if (_definitions === null) {
        const blob = dsviper.ValueBlob.base64Decode(B64_DEFINITIONS);
        const defs = dsviper.Definitions.decode(blob);
        _definitions = defs.const();
    }
    return _definitions;
}

// Concept / club / enum / struct runtime ids
export const RuntimeIds = {
    // Namespace Test
    Test_ConceptA: dsviper.ValueUUId.create("bcc4e978-a438-ddba-66b9-d767b3b2649e"),
    Test_ConceptB: dsviper.ValueUUId.create("cdb6cd9f-f1b4-03b0-dff8-b8a2092ec01c"),
    Test_ConceptC: dsviper.ValueUUId.create("ce7c9e3d-ae5f-2e57-c693-4b3e351d105b"),
    Test_ConceptD: dsviper.ValueUUId.create("edc1351f-a74f-2036-f170-e1a67570b90a"),
    Test_Klub: dsviper.ValueUUId.create("0e64c619-6b27-330c-52ca-d2b0b6d88c0a"),
    Test_EnumerationE: dsviper.ValueUUId.create("57233334-ee71-b77f-d6a6-b4ff25bb2350"),
    Test_StructureS: dsviper.ValueUUId.create("c4f62cf6-2d27-05b0-018c-67d1b99df4a6"),
    Test_StructureT: dsviper.ValueUUId.create("773ad0a2-1c7b-302e-e1b5-314ab0edb74a"),
    Test_StructureU: dsviper.ValueUUId.create("fc7a32c3-3600-dd9a-110c-44830b3b859e"),
    Test_StructureV: dsviper.ValueUUId.create("8b5d06ab-5a9f-d427-23b8-7ec3611aabde"),
};

// Attachment runtime ids
export const AttachmentRuntimeIds = {
    // Namespace Test
    Test_Any_concept_PropertiesAnyConceptAny: dsviper.ValueUUId.create("8de8e47b-58e8-5699-59a7-5a3193aef7f1"),
    Test_ConceptA_Properties: dsviper.ValueUUId.create("3b79131f-a619-5b33-66ab-3b78ca749cd0"),
    Test_ConceptA_PropertiesInt8: dsviper.ValueUUId.create("58ce283d-b8eb-1f01-3841-854fccd54fd7"),
    Test_ConceptA_PropertiesMapInt8String: dsviper.ValueUUId.create("0eb140e3-5247-d7ad-649f-5fa124359ee2"),
    Test_ConceptA_PropertiesSeInt8: dsviper.ValueUUId.create("ad45f798-b25a-0421-c523-713ff624383e"),
    Test_ConceptA_PropertiesXArray: dsviper.ValueUUId.create("ff9d7eda-5ad0-d217-d910-7d2adfad208f"),
    Test_ConceptB_PropertiesB: dsviper.ValueUUId.create("c117fd64-7b82-f4ab-164c-efb528a408bc"),
    Test_ConceptC_PropertiesC: dsviper.ValueUUId.create("89744936-fa08-e52d-3b39-8fffdee0a93a"),
    Test_Klub_PropertiesD: dsviper.ValueUUId.create("f7a9f794-cedc-a3ff-9530-63f86e932850"),
};