// Generated by kibo from features. Do not edit by hand.
// Templates: kibo-template-viper 1.2.1 (MIT).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Features.dsm.json by kibo-1.2.11.jar

/**
 * Viper Definitions and runtime ids for features.
 */

import dsviper from "@digitalsubstrate/dsviper";
import { B64_DEFINITIONS } from "./resources.js";

let _definitions: dsviper.DefinitionsConst | null = null;

export function definitions(): dsviper.DefinitionsConst {
    if (_definitions === null) {
        const blob = dsviper.ValueBlob.base64Decode(B64_DEFINITIONS);
        const defs = dsviper.Definitions.decode(blob);
        _definitions = defs.const();
    }
    return _definitions;
}

// Concept / club / enum / struct runtime ids
export const RuntimeIds = {
    // Namespace Test
    Test_ConceptA: dsviper.ValueUUId.create("bcc4e978-a438-ddba-66b9-d767b3b2649e"),
    Test_ConceptB: dsviper.ValueUUId.create("cdb6cd9f-f1b4-03b0-dff8-b8a2092ec01c"),
    Test_ConceptC: dsviper.ValueUUId.create("ce7c9e3d-ae5f-2e57-c693-4b3e351d105b"),
    Test_ConceptCoverage: dsviper.ValueUUId.create("28892760-a292-acbb-40ba-1aa63fc833e6"),
    Test_ConceptD: dsviper.ValueUUId.create("edc1351f-a74f-2036-f170-e1a67570b90a"),
    Test_EmptyKlub: dsviper.ValueUUId.create("f1a3dba5-200b-4fb9-e8e7-a5a62af2a843"),
    Test_Klub: dsviper.ValueUUId.create("0e64c619-6b27-330c-52ca-d2b0b6d88c0a"),
    Test_EnumerationE: dsviper.ValueUUId.create("57233334-ee71-b77f-d6a6-b4ff25bb2350"),
    Test_StructureS: dsviper.ValueUUId.create("c4f62cf6-2d27-05b0-018c-67d1b99df4a6"),
    Test_StructureT: dsviper.ValueUUId.create("773ad0a2-1c7b-302e-e1b5-314ab0edb74a"),
    Test_StructureU: dsviper.ValueUUId.create("019d066d-bd5a-19b7-4565-9c5a6f95c808"),
    Test_StructureV: dsviper.ValueUUId.create("8b5d06ab-5a9f-d427-23b8-7ec3611aabde"),
    Test_StructureW: dsviper.ValueUUId.create("df0e54fc-b3ac-a527-d8d7-678fc2d56d3f"),
};

// Attachment runtime ids
export const AttachmentRuntimeIds = {
    // Namespace Test
    Test_Any_concept_PropertiesAnyConceptAny: dsviper.ValueUUId.create("8de8e47b-58e8-5699-59a7-5a3193aef7f1"),
    Test_ConceptA_Properties: dsviper.ValueUUId.create("3b79131f-a619-5b33-66ab-3b78ca749cd0"),
    Test_ConceptA_PropertiesInt8: dsviper.ValueUUId.create("58ce283d-b8eb-1f01-3841-854fccd54fd7"),
    Test_ConceptA_PropertiesMapInt8String: dsviper.ValueUUId.create("0eb140e3-5247-d7ad-649f-5fa124359ee2"),
    Test_ConceptA_PropertiesSeInt8: dsviper.ValueUUId.create("ad45f798-b25a-0421-c523-713ff624383e"),
    Test_ConceptA_PropertiesXArray: dsviper.ValueUUId.create("ff9d7eda-5ad0-d217-d910-7d2adfad208f"),
    Test_ConceptB_PropertiesB: dsviper.ValueUUId.create("c117fd64-7b82-f4ab-164c-efb528a408bc"),
    Test_ConceptC_PropertiesC: dsviper.ValueUUId.create("7f6d8d89-d32a-3214-ed11-3f23b7faaf1e"),
    Test_ConceptCoverage_DocAny: dsviper.ValueUUId.create("20a71745-30fb-4f1b-2245-d331c323bbba"),
    Test_ConceptCoverage_DocAnyConceptKey: dsviper.ValueUUId.create("ab54b0a8-596a-40fc-6ef1-f1d2eba54f5c"),
    Test_ConceptCoverage_DocBlob: dsviper.ValueUUId.create("e80aaf93-0656-f497-1372-20158ecea8fb"),
    Test_ConceptCoverage_DocBlobId: dsviper.ValueUUId.create("8dce567e-111b-bddf-7448-1abc8261ac90"),
    Test_ConceptCoverage_DocBool: dsviper.ValueUUId.create("de0efd5b-90bb-216f-03f8-cbf32245a423"),
    Test_ConceptCoverage_DocClubKey: dsviper.ValueUUId.create("6c8c6c4a-f99b-1737-f3e9-b60da806f18b"),
    Test_ConceptCoverage_DocCommitId: dsviper.ValueUUId.create("8bc4885f-0e59-2156-6534-f71674e16a62"),
    Test_ConceptCoverage_DocConceptKey: dsviper.ValueUUId.create("e46092d8-19d2-786f-8ec2-ffe4eb96a2b0"),
    Test_ConceptCoverage_DocConceptKeyB: dsviper.ValueUUId.create("72eb0057-8f6c-7e05-f68e-36ec9bbdc0e6"),
    Test_ConceptCoverage_DocDouble: dsviper.ValueUUId.create("ddcc4ebf-809b-1186-a81d-e04887a55c28"),
    Test_ConceptCoverage_DocEnumeration: dsviper.ValueUUId.create("297e6910-d347-da0c-3dd6-563406dc742f"),
    Test_ConceptCoverage_DocFloat: dsviper.ValueUUId.create("59dc723c-e718-31bd-93e1-fce13b975469"),
    Test_ConceptCoverage_DocInt16: dsviper.ValueUUId.create("138e62f6-c93a-11e6-8cbb-582c7de65a27"),
    Test_ConceptCoverage_DocInt32: dsviper.ValueUUId.create("83d4d1bf-497b-e2ad-4efc-09509903ef47"),
    Test_ConceptCoverage_DocInt64: dsviper.ValueUUId.create("bb3c8bde-0fd6-0535-4a63-361ba70dbe9c"),
    Test_ConceptCoverage_DocInt8: dsviper.ValueUUId.create("0eb18fdd-6c1b-1584-34c8-f8356d4bc05d"),
    Test_ConceptCoverage_DocMap: dsviper.ValueUUId.create("d06b8489-8bd1-a8ff-4e64-d95c5771208f"),
    Test_ConceptCoverage_DocMat: dsviper.ValueUUId.create("43e79483-eead-0925-cedd-78a45ce47d98"),
    Test_ConceptCoverage_DocOptional: dsviper.ValueUUId.create("92e537a9-7a80-e98f-6e44-8a463cf9a970"),
    Test_ConceptCoverage_DocSet: dsviper.ValueUUId.create("7793f2b3-58ab-a3a3-bd44-04cf41b58cdc"),
    Test_ConceptCoverage_DocString: dsviper.ValueUUId.create("9403f10d-288e-00cc-1169-f9a544777dbc"),
    Test_ConceptCoverage_DocStructureSingleField: dsviper.ValueUUId.create("19ebae3f-d189-04a2-dea3-deb80ece9ff8"),
    Test_ConceptCoverage_DocTuple: dsviper.ValueUUId.create("d51d4c9f-f9cd-fe62-4417-28021df7961c"),
    Test_ConceptCoverage_DocUInt16: dsviper.ValueUUId.create("3ae2904f-b0ed-d9e8-448a-fbd6d80be212"),
    Test_ConceptCoverage_DocUInt32: dsviper.ValueUUId.create("85ced0f5-1127-8750-a18e-3ecbfbe4813a"),
    Test_ConceptCoverage_DocUInt64: dsviper.ValueUUId.create("00a3fbe9-15b1-8e1f-fc42-c01d845ccc9a"),
    Test_ConceptCoverage_DocUInt8: dsviper.ValueUUId.create("5ac282e6-15c4-0a8c-bab9-b14ac6a7f9ed"),
    Test_ConceptCoverage_DocUUId: dsviper.ValueUUId.create("a79058d8-5ee7-303d-1d19-50f01983a35b"),
    Test_ConceptCoverage_DocVariant: dsviper.ValueUUId.create("b7a81faa-fea8-a2cb-760b-edf353f16c63"),
    Test_ConceptCoverage_DocVec: dsviper.ValueUUId.create("73d224c0-d38f-4b5a-d225-bad481cec150"),
    Test_ConceptCoverage_DocVector: dsviper.ValueUUId.create("ebb21187-7004-e7fa-23e6-690803352742"),
    Test_ConceptCoverage_DocXArray: dsviper.ValueUUId.create("d45a1e55-9fc4-037e-5ce7-856093a638be"),
    Test_Klub_PropertiesD: dsviper.ValueUUId.create("f7a9f794-cedc-a3ff-9530-63f86e932850"),
};