// Generated by kibo from features. Do not edit by hand.
// Templates: kibo-template-viper 1.2.1 (MIT).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Features.dsm.json by kibo-1.2.11.jar

import dsviper from "@digitalsubstrate/dsviper";

export const Path_Root: dsviper.PathConst = new dsviper.Path().const();

// Namespace Test
export class Test_Path_StructureS {
    static readonly f_float: dsviper.PathConst = dsviper.Path.fromField("f_float").const();
    static readonly f_string: dsviper.PathConst = dsviper.Path.fromField("f_string").const();
}

export class Test_Path_StructureT {
    static readonly field_string: dsviper.PathConst = dsviper.Path.fromField("field_string").const();
    static readonly field_structure_s: dsviper.PathConst = dsviper.Path.fromField("field_structure_s").const();
}

export class Test_Path_StructureU {
    static readonly f_bool: dsviper.PathConst = dsviper.Path.fromField("f_bool").const();
    static readonly f_uint8: dsviper.PathConst = dsviper.Path.fromField("f_uint8").const();
    static readonly f_uint16: dsviper.PathConst = dsviper.Path.fromField("f_uint16").const();
    static readonly f_uint32: dsviper.PathConst = dsviper.Path.fromField("f_uint32").const();
    static readonly f_uint64: dsviper.PathConst = dsviper.Path.fromField("f_uint64").const();
    static readonly f_int8: dsviper.PathConst = dsviper.Path.fromField("f_int8").const();
    static readonly f_int16: dsviper.PathConst = dsviper.Path.fromField("f_int16").const();
    static readonly f_int32: dsviper.PathConst = dsviper.Path.fromField("f_int32").const();
    static readonly f_int64: dsviper.PathConst = dsviper.Path.fromField("f_int64").const();
    static readonly f_float: dsviper.PathConst = dsviper.Path.fromField("f_float").const();
    static readonly f_double: dsviper.PathConst = dsviper.Path.fromField("f_double").const();
    static readonly f_blob_id: dsviper.PathConst = dsviper.Path.fromField("f_blob_id").const();
    static readonly f_commit_id: dsviper.PathConst = dsviper.Path.fromField("f_commit_id").const();
    static readonly f_uuid: dsviper.PathConst = dsviper.Path.fromField("f_uuid").const();
    static readonly f_string: dsviper.PathConst = dsviper.Path.fromField("f_string").const();
    static readonly f_blob: dsviper.PathConst = dsviper.Path.fromField("f_blob").const();
    static readonly f_vec: dsviper.PathConst = dsviper.Path.fromField("f_vec").const();
    static readonly f_mat: dsviper.PathConst = dsviper.Path.fromField("f_mat").const();
    static readonly f_tuple: dsviper.PathConst = dsviper.Path.fromField("f_tuple").const();
    static readonly f_optional: dsviper.PathConst = dsviper.Path.fromField("f_optional").const();
    static readonly f_vector: dsviper.PathConst = dsviper.Path.fromField("f_vector").const();
    static readonly f_set: dsviper.PathConst = dsviper.Path.fromField("f_set").const();
    static readonly f_set_s: dsviper.PathConst = dsviper.Path.fromField("f_set_s").const();
    static readonly f_map_s1: dsviper.PathConst = dsviper.Path.fromField("f_map_s1").const();
    static readonly f_map_s2: dsviper.PathConst = dsviper.Path.fromField("f_map_s2").const();
    static readonly f_xarray: dsviper.PathConst = dsviper.Path.fromField("f_xarray").const();
    static readonly f_xarray_s: dsviper.PathConst = dsviper.Path.fromField("f_xarray_s").const();
    static readonly f_map_vs: dsviper.PathConst = dsviper.Path.fromField("f_map_vs").const();
    static readonly f_variant: dsviper.PathConst = dsviper.Path.fromField("f_variant").const();
    static readonly f_any: dsviper.PathConst = dsviper.Path.fromField("f_any").const();
    static readonly f_E: dsviper.PathConst = dsviper.Path.fromField("f_E").const();
    static readonly f_S: dsviper.PathConst = dsviper.Path.fromField("f_S").const();
    static readonly f_T: dsviper.PathConst = dsviper.Path.fromField("f_T").const();
    static readonly f_A: dsviper.PathConst = dsviper.Path.fromField("f_A").const();
    static readonly f_B: dsviper.PathConst = dsviper.Path.fromField("f_B").const();
    static readonly f_C: dsviper.PathConst = dsviper.Path.fromField("f_C").const();
    static readonly f_D: dsviper.PathConst = dsviper.Path.fromField("f_D").const();
    static readonly f_Klub: dsviper.PathConst = dsviper.Path.fromField("f_Klub").const();
    static readonly f_any_concept: dsviper.PathConst = dsviper.Path.fromField("f_any_concept").const();
}

export class Test_Path_StructureV {
    static readonly f_bool: dsviper.PathConst = dsviper.Path.fromField("f_bool").const();
    static readonly f_uint8: dsviper.PathConst = dsviper.Path.fromField("f_uint8").const();
    static readonly f_uint16: dsviper.PathConst = dsviper.Path.fromField("f_uint16").const();
    static readonly f_uint32: dsviper.PathConst = dsviper.Path.fromField("f_uint32").const();
    static readonly f_uint64: dsviper.PathConst = dsviper.Path.fromField("f_uint64").const();
    static readonly f_int8: dsviper.PathConst = dsviper.Path.fromField("f_int8").const();
    static readonly f_int16: dsviper.PathConst = dsviper.Path.fromField("f_int16").const();
    static readonly f_int32: dsviper.PathConst = dsviper.Path.fromField("f_int32").const();
    static readonly f_int64: dsviper.PathConst = dsviper.Path.fromField("f_int64").const();
    static readonly f_float: dsviper.PathConst = dsviper.Path.fromField("f_float").const();
    static readonly f_double: dsviper.PathConst = dsviper.Path.fromField("f_double").const();
    static readonly f_uuid: dsviper.PathConst = dsviper.Path.fromField("f_uuid").const();
    static readonly f_string: dsviper.PathConst = dsviper.Path.fromField("f_string").const();
    static readonly f_vec: dsviper.PathConst = dsviper.Path.fromField("f_vec").const();
    static readonly f_mat: dsviper.PathConst = dsviper.Path.fromField("f_mat").const();
    static readonly f_tuple: dsviper.PathConst = dsviper.Path.fromField("f_tuple").const();
    static readonly f_optional: dsviper.PathConst = dsviper.Path.fromField("f_optional").const();
    static readonly f_vector: dsviper.PathConst = dsviper.Path.fromField("f_vector").const();
    static readonly f_set: dsviper.PathConst = dsviper.Path.fromField("f_set").const();
    static readonly f_map: dsviper.PathConst = dsviper.Path.fromField("f_map").const();
    static readonly f_E: dsviper.PathConst = dsviper.Path.fromField("f_E").const();
    static readonly f_S: dsviper.PathConst = dsviper.Path.fromField("f_S").const();
    static readonly f_T: dsviper.PathConst = dsviper.Path.fromField("f_T").const();
}

export class Test_Path_StructureW {
    static readonly f_single: dsviper.PathConst = dsviper.Path.fromField("f_single").const();
}
