// Generated by kibo from features. Do not edit by hand.
// Templates: kibo-template-viper 1.2.1 (MIT).
// Runtime: this file imports `@digitalsubstrate/dsviper`, distributed under
// LicenseRef-DigitalSubstrate-Commercial-1.2. Commercial use
// requires a Commercial Licence from Digital Substrate.
// Generated from Features.dsm.json by kibo-1.2.11.jar

/**
 * Viper types for concepts, clubs, enums, structs and all containers defined for features.
 */

import dsviper from "@digitalsubstrate/dsviper";
import * as md from "./definitions.js";

let _type_void: dsviper.TypeVoid | null = null;
export function type_void(): dsviper.TypeVoid {
    if (_type_void === null) { _type_void = new dsviper.TypeVoid(); }
    return _type_void;
}

// Numbers
let _type_bool: dsviper.TypeBool | null = null;
export function type_bool(): dsviper.TypeBool {
    if (_type_bool === null) { _type_bool = new dsviper.TypeBool(); }
    return _type_bool;
}

let _type_uint8: dsviper.TypeUInt8 | null = null;
export function type_uint8(): dsviper.TypeUInt8 {
    if (_type_uint8 === null) { _type_uint8 = new dsviper.TypeUInt8(); }
    return _type_uint8;
}

let _type_uint16: dsviper.TypeUInt16 | null = null;
export function type_uint16(): dsviper.TypeUInt16 {
    if (_type_uint16 === null) { _type_uint16 = new dsviper.TypeUInt16(); }
    return _type_uint16;
}

let _type_uint32: dsviper.TypeUInt32 | null = null;
export function type_uint32(): dsviper.TypeUInt32 {
    if (_type_uint32 === null) { _type_uint32 = new dsviper.TypeUInt32(); }
    return _type_uint32;
}

let _type_uint64: dsviper.TypeUInt64 | null = null;
export function type_uint64(): dsviper.TypeUInt64 {
    if (_type_uint64 === null) { _type_uint64 = new dsviper.TypeUInt64(); }
    return _type_uint64;
}

let _type_int8: dsviper.TypeInt8 | null = null;
export function type_int8(): dsviper.TypeInt8 {
    if (_type_int8 === null) { _type_int8 = new dsviper.TypeInt8(); }
    return _type_int8;
}

let _type_int16: dsviper.TypeInt16 | null = null;
export function type_int16(): dsviper.TypeInt16 {
    if (_type_int16 === null) { _type_int16 = new dsviper.TypeInt16(); }
    return _type_int16;
}

let _type_int32: dsviper.TypeInt32 | null = null;
export function type_int32(): dsviper.TypeInt32 {
    if (_type_int32 === null) { _type_int32 = new dsviper.TypeInt32(); }
    return _type_int32;
}

let _type_int64: dsviper.TypeInt64 | null = null;
export function type_int64(): dsviper.TypeInt64 {
    if (_type_int64 === null) { _type_int64 = new dsviper.TypeInt64(); }
    return _type_int64;
}

let _type_float: dsviper.TypeFloat | null = null;
export function type_float(): dsviper.TypeFloat {
    if (_type_float === null) { _type_float = new dsviper.TypeFloat(); }
    return _type_float;
}

let _type_double: dsviper.TypeDouble | null = null;
export function type_double(): dsviper.TypeDouble {
    if (_type_double === null) { _type_double = new dsviper.TypeDouble(); }
    return _type_double;
}

// Ids
let _type_blob_id: dsviper.TypeBlobId | null = null;
export function type_blob_id(): dsviper.TypeBlobId {
    if (_type_blob_id === null) { _type_blob_id = new dsviper.TypeBlobId(); }
    return _type_blob_id;
}

let _type_commit_id: dsviper.TypeCommitId | null = null;
export function type_commit_id(): dsviper.TypeCommitId {
    if (_type_commit_id === null) { _type_commit_id = new dsviper.TypeCommitId(); }
    return _type_commit_id;
}

let _type_uuid: dsviper.TypeUUId | null = null;
export function type_uuid(): dsviper.TypeUUId {
    if (_type_uuid === null) { _type_uuid = new dsviper.TypeUUId(); }
    return _type_uuid;
}

// String & Blob
let _type_string: dsviper.TypeString | null = null;
export function type_string(): dsviper.TypeString {
    if (_type_string === null) { _type_string = new dsviper.TypeString(); }
    return _type_string;
}

let _type_blob: dsviper.TypeBlob | null = null;
export function type_blob(): dsviper.TypeBlob {
    if (_type_blob === null) { _type_blob = new dsviper.TypeBlob(); }
    return _type_blob;
}

// Any (runtime singleton)
export function type_any(): dsviper.TypeAny {
    return dsviper.Type.ANY;
}

// AnyConcept (runtime singleton)
export function type_def_any_concept(): dsviper.TypeAnyConcept {
    return dsviper.Type.ANY_CONCEPT;
}

let _type_AnyConceptKey: dsviper.TypeKey | null = null;
export function type_AnyConceptKey(): dsviper.TypeKey {
    if (_type_AnyConceptKey === null) { _type_AnyConceptKey = new dsviper.TypeKey(type_def_any_concept()); }
    return _type_AnyConceptKey;
}

// Vecs
let _type_vec2_uint8: dsviper.TypeVec | null = null;
export function type_vec2_uint8(): dsviper.TypeVec {
    if (_type_vec2_uint8 === null) { _type_vec2_uint8 = new dsviper.TypeVec(type_uint8(), 2); }
    return _type_vec2_uint8;
}


// Mats
let _type_mat2x2_uint8: dsviper.TypeMat | null = null;
export function type_mat2x2_uint8(): dsviper.TypeMat {
    if (_type_mat2x2_uint8 === null) { _type_mat2x2_uint8 = new dsviper.TypeMat(type_uint8(), 2, 2); }
    return _type_mat2x2_uint8;
}

let _type_mat2x3_uint8: dsviper.TypeMat | null = null;
export function type_mat2x3_uint8(): dsviper.TypeMat {
    if (_type_mat2x3_uint8 === null) { _type_mat2x3_uint8 = new dsviper.TypeMat(type_uint8(), 2, 3); }
    return _type_mat2x3_uint8;
}


// Tuples
let _type_tuple_uint8_string: dsviper.TypeTuple | null = null;
export function type_tuple_uint8_string(): dsviper.TypeTuple {
    if (_type_tuple_uint8_string === null) {
        const types = [type_uint8(), type_string()];
        _type_tuple_uint8_string = new dsviper.TypeTuple(types);
    }
    return _type_tuple_uint8_string;
}


// Optionals
let _type_optional_uint8: dsviper.TypeOptional | null = null;
export function type_optional_uint8(): dsviper.TypeOptional {
    if (_type_optional_uint8 === null) { _type_optional_uint8 = new dsviper.TypeOptional(type_uint8()); }
    return _type_optional_uint8;
}


// Vectors
let _type_vector_Test_StructureS: dsviper.TypeVector | null = null;
export function type_vector_Test_StructureS(): dsviper.TypeVector {
    if (_type_vector_Test_StructureS === null) { _type_vector_Test_StructureS = new dsviper.TypeVector(type_Test_StructureS()); }
    return _type_vector_Test_StructureS;
}

let _type_vector_uint8: dsviper.TypeVector | null = null;
export function type_vector_uint8(): dsviper.TypeVector {
    if (_type_vector_uint8 === null) { _type_vector_uint8 = new dsviper.TypeVector(type_uint8()); }
    return _type_vector_uint8;
}


// Sets
let _type_set_Test_StructureS: dsviper.TypeSet | null = null;
export function type_set_Test_StructureS(): dsviper.TypeSet {
    if (_type_set_Test_StructureS === null) { _type_set_Test_StructureS = new dsviper.TypeSet(type_Test_StructureS()); }
    return _type_set_Test_StructureS;
}

let _type_set_int8: dsviper.TypeSet | null = null;
export function type_set_int8(): dsviper.TypeSet {
    if (_type_set_int8 === null) { _type_set_int8 = new dsviper.TypeSet(type_int8()); }
    return _type_set_int8;
}

let _type_set_string: dsviper.TypeSet | null = null;
export function type_set_string(): dsviper.TypeSet {
    if (_type_set_string === null) { _type_set_string = new dsviper.TypeSet(type_string()); }
    return _type_set_string;
}

let _type_set_uint8: dsviper.TypeSet | null = null;
export function type_set_uint8(): dsviper.TypeSet {
    if (_type_set_uint8 === null) { _type_set_uint8 = new dsviper.TypeSet(type_uint8()); }
    return _type_set_uint8;
}

let _type_set_vector_Test_StructureS: dsviper.TypeSet | null = null;
export function type_set_vector_Test_StructureS(): dsviper.TypeSet {
    if (_type_set_vector_Test_StructureS === null) { _type_set_vector_Test_StructureS = new dsviper.TypeSet(type_vector_Test_StructureS()); }
    return _type_set_vector_Test_StructureS;
}


// Maps
let _type_map_Test_StructureS_to_string: dsviper.TypeMap | null = null;
export function type_map_Test_StructureS_to_string(): dsviper.TypeMap {
    if (_type_map_Test_StructureS_to_string === null) { _type_map_Test_StructureS_to_string = new dsviper.TypeMap(type_Test_StructureS(), type_string()); }
    return _type_map_Test_StructureS_to_string;
}

let _type_map_int8_to_string: dsviper.TypeMap | null = null;
export function type_map_int8_to_string(): dsviper.TypeMap {
    if (_type_map_int8_to_string === null) { _type_map_int8_to_string = new dsviper.TypeMap(type_int8(), type_string()); }
    return _type_map_int8_to_string;
}

let _type_map_string_to_Test_StructureS: dsviper.TypeMap | null = null;
export function type_map_string_to_Test_StructureS(): dsviper.TypeMap {
    if (_type_map_string_to_Test_StructureS === null) { _type_map_string_to_Test_StructureS = new dsviper.TypeMap(type_string(), type_Test_StructureS()); }
    return _type_map_string_to_Test_StructureS;
}

let _type_map_uint8_to_string: dsviper.TypeMap | null = null;
export function type_map_uint8_to_string(): dsviper.TypeMap {
    if (_type_map_uint8_to_string === null) { _type_map_uint8_to_string = new dsviper.TypeMap(type_uint8(), type_string()); }
    return _type_map_uint8_to_string;
}

let _type_map_vector_Test_StructureS_to_string: dsviper.TypeMap | null = null;
export function type_map_vector_Test_StructureS_to_string(): dsviper.TypeMap {
    if (_type_map_vector_Test_StructureS_to_string === null) { _type_map_vector_Test_StructureS_to_string = new dsviper.TypeMap(type_vector_Test_StructureS(), type_string()); }
    return _type_map_vector_Test_StructureS_to_string;
}


// XArrays
let _type_xarray_Test_StructureS: dsviper.TypeXArray | null = null;
export function type_xarray_Test_StructureS(): dsviper.TypeXArray {
    if (_type_xarray_Test_StructureS === null) { _type_xarray_Test_StructureS = new dsviper.TypeXArray(type_Test_StructureS()); }
    return _type_xarray_Test_StructureS;
}

let _type_xarray_int8: dsviper.TypeXArray | null = null;
export function type_xarray_int8(): dsviper.TypeXArray {
    if (_type_xarray_int8 === null) { _type_xarray_int8 = new dsviper.TypeXArray(type_int8()); }
    return _type_xarray_int8;
}

let _type_xarray_uint8: dsviper.TypeXArray | null = null;
export function type_xarray_uint8(): dsviper.TypeXArray {
    if (_type_xarray_uint8 === null) { _type_xarray_uint8 = new dsviper.TypeXArray(type_uint8()); }
    return _type_xarray_uint8;
}


// Variants
let _type_variant_string_uint8_Test_StructureS: dsviper.TypeVariant | null = null;
export function type_variant_string_uint8_Test_StructureS(): dsviper.TypeVariant {
    if (_type_variant_string_uint8_Test_StructureS === null) {
        const types = [type_string(), type_uint8(), type_Test_StructureS()];
        _type_variant_string_uint8_Test_StructureS = new dsviper.TypeVariant(types);
    }
    return _type_variant_string_uint8_Test_StructureS;
}

let _type_variant_string_uint8: dsviper.TypeVariant | null = null;
export function type_variant_string_uint8(): dsviper.TypeVariant {
    if (_type_variant_string_uint8 === null) {
        const types = [type_string(), type_uint8()];
        _type_variant_string_uint8 = new dsviper.TypeVariant(types);
    }
    return _type_variant_string_uint8;
}


// Namespace Test
let _type_check_Test_ConceptAKey: dsviper.TypeConcept | null = null;
export function type_check_Test_ConceptAKey(): dsviper.TypeConcept {
    if (_type_check_Test_ConceptAKey === null) { _type_check_Test_ConceptAKey = md.definitions().checkConcept(md.RuntimeIds.Test_ConceptA); }
    return _type_check_Test_ConceptAKey;
}

let _type_Test_ConceptAKey: dsviper.TypeKey | null = null;
export function type_Test_ConceptAKey(): dsviper.TypeKey {
    if (_type_Test_ConceptAKey === null) { _type_Test_ConceptAKey = new dsviper.TypeKey(type_check_Test_ConceptAKey()); }
    return _type_Test_ConceptAKey;
}

let _type_check_Test_ConceptBKey: dsviper.TypeConcept | null = null;
export function type_check_Test_ConceptBKey(): dsviper.TypeConcept {
    if (_type_check_Test_ConceptBKey === null) { _type_check_Test_ConceptBKey = md.definitions().checkConcept(md.RuntimeIds.Test_ConceptB); }
    return _type_check_Test_ConceptBKey;
}

let _type_Test_ConceptBKey: dsviper.TypeKey | null = null;
export function type_Test_ConceptBKey(): dsviper.TypeKey {
    if (_type_Test_ConceptBKey === null) { _type_Test_ConceptBKey = new dsviper.TypeKey(type_check_Test_ConceptBKey()); }
    return _type_Test_ConceptBKey;
}

let _type_check_Test_ConceptCKey: dsviper.TypeConcept | null = null;
export function type_check_Test_ConceptCKey(): dsviper.TypeConcept {
    if (_type_check_Test_ConceptCKey === null) { _type_check_Test_ConceptCKey = md.definitions().checkConcept(md.RuntimeIds.Test_ConceptC); }
    return _type_check_Test_ConceptCKey;
}

let _type_Test_ConceptCKey: dsviper.TypeKey | null = null;
export function type_Test_ConceptCKey(): dsviper.TypeKey {
    if (_type_Test_ConceptCKey === null) { _type_Test_ConceptCKey = new dsviper.TypeKey(type_check_Test_ConceptCKey()); }
    return _type_Test_ConceptCKey;
}

let _type_check_Test_ConceptCoverageKey: dsviper.TypeConcept | null = null;
export function type_check_Test_ConceptCoverageKey(): dsviper.TypeConcept {
    if (_type_check_Test_ConceptCoverageKey === null) { _type_check_Test_ConceptCoverageKey = md.definitions().checkConcept(md.RuntimeIds.Test_ConceptCoverage); }
    return _type_check_Test_ConceptCoverageKey;
}

let _type_Test_ConceptCoverageKey: dsviper.TypeKey | null = null;
export function type_Test_ConceptCoverageKey(): dsviper.TypeKey {
    if (_type_Test_ConceptCoverageKey === null) { _type_Test_ConceptCoverageKey = new dsviper.TypeKey(type_check_Test_ConceptCoverageKey()); }
    return _type_Test_ConceptCoverageKey;
}

let _type_check_Test_ConceptDKey: dsviper.TypeConcept | null = null;
export function type_check_Test_ConceptDKey(): dsviper.TypeConcept {
    if (_type_check_Test_ConceptDKey === null) { _type_check_Test_ConceptDKey = md.definitions().checkConcept(md.RuntimeIds.Test_ConceptD); }
    return _type_check_Test_ConceptDKey;
}

let _type_Test_ConceptDKey: dsviper.TypeKey | null = null;
export function type_Test_ConceptDKey(): dsviper.TypeKey {
    if (_type_Test_ConceptDKey === null) { _type_Test_ConceptDKey = new dsviper.TypeKey(type_check_Test_ConceptDKey()); }
    return _type_Test_ConceptDKey;
}

let _type_check_Test_EmptyKlubKey: dsviper.TypeClub | null = null;
export function type_check_Test_EmptyKlubKey(): dsviper.TypeClub {
    if (_type_check_Test_EmptyKlubKey === null) { _type_check_Test_EmptyKlubKey = md.definitions().checkClub(md.RuntimeIds.Test_EmptyKlub); }
    return _type_check_Test_EmptyKlubKey;
}

let _type_Test_EmptyKlubKey: dsviper.TypeKey | null = null;
export function type_Test_EmptyKlubKey(): dsviper.TypeKey {
    if (_type_Test_EmptyKlubKey === null) { _type_Test_EmptyKlubKey = new dsviper.TypeKey(type_check_Test_EmptyKlubKey()); }
    return _type_Test_EmptyKlubKey;
}

let _type_check_Test_KlubKey: dsviper.TypeClub | null = null;
export function type_check_Test_KlubKey(): dsviper.TypeClub {
    if (_type_check_Test_KlubKey === null) { _type_check_Test_KlubKey = md.definitions().checkClub(md.RuntimeIds.Test_Klub); }
    return _type_check_Test_KlubKey;
}

let _type_Test_KlubKey: dsviper.TypeKey | null = null;
export function type_Test_KlubKey(): dsviper.TypeKey {
    if (_type_Test_KlubKey === null) { _type_Test_KlubKey = new dsviper.TypeKey(type_check_Test_KlubKey()); }
    return _type_Test_KlubKey;
}

let _type_Test_EnumerationE: dsviper.TypeEnumeration | null = null;
export function type_Test_EnumerationE(): dsviper.TypeEnumeration {
    if (_type_Test_EnumerationE === null) { _type_Test_EnumerationE = md.definitions().checkEnumeration(md.RuntimeIds.Test_EnumerationE); }
    return _type_Test_EnumerationE;
}

let _type_Test_StructureS: dsviper.TypeStructure | null = null;
export function type_Test_StructureS(): dsviper.TypeStructure {
    if (_type_Test_StructureS === null) { _type_Test_StructureS = md.definitions().checkStructure(md.RuntimeIds.Test_StructureS); }
    return _type_Test_StructureS;
}

let _type_Test_StructureT: dsviper.TypeStructure | null = null;
export function type_Test_StructureT(): dsviper.TypeStructure {
    if (_type_Test_StructureT === null) { _type_Test_StructureT = md.definitions().checkStructure(md.RuntimeIds.Test_StructureT); }
    return _type_Test_StructureT;
}

let _type_Test_StructureU: dsviper.TypeStructure | null = null;
export function type_Test_StructureU(): dsviper.TypeStructure {
    if (_type_Test_StructureU === null) { _type_Test_StructureU = md.definitions().checkStructure(md.RuntimeIds.Test_StructureU); }
    return _type_Test_StructureU;
}

let _type_Test_StructureV: dsviper.TypeStructure | null = null;
export function type_Test_StructureV(): dsviper.TypeStructure {
    if (_type_Test_StructureV === null) { _type_Test_StructureV = md.definitions().checkStructure(md.RuntimeIds.Test_StructureV); }
    return _type_Test_StructureV;
}

let _type_Test_StructureW: dsviper.TypeStructure | null = null;
export function type_Test_StructureW(): dsviper.TypeStructure {
    if (_type_Test_StructureW === null) { _type_Test_StructureW = md.definitions().checkStructure(md.RuntimeIds.Test_StructureW); }
    return _type_Test_StructureW;
}

let _attachment_Test_Any_concept_PropertiesAnyConceptAny: dsviper.Attachment | null = null;
export function attachment_Test_Any_concept_PropertiesAnyConceptAny(): dsviper.Attachment {
    if (_attachment_Test_Any_concept_PropertiesAnyConceptAny === null) { _attachment_Test_Any_concept_PropertiesAnyConceptAny = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Any_concept_PropertiesAnyConceptAny); }
    return _attachment_Test_Any_concept_PropertiesAnyConceptAny;
}

let _attachment_Test_ConceptA_Properties: dsviper.Attachment | null = null;
export function attachment_Test_ConceptA_Properties(): dsviper.Attachment {
    if (_attachment_Test_ConceptA_Properties === null) { _attachment_Test_ConceptA_Properties = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_Properties); }
    return _attachment_Test_ConceptA_Properties;
}

let _attachment_Test_ConceptA_PropertiesInt8: dsviper.Attachment | null = null;
export function attachment_Test_ConceptA_PropertiesInt8(): dsviper.Attachment {
    if (_attachment_Test_ConceptA_PropertiesInt8 === null) { _attachment_Test_ConceptA_PropertiesInt8 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesInt8); }
    return _attachment_Test_ConceptA_PropertiesInt8;
}

let _attachment_Test_ConceptA_PropertiesMapInt8String: dsviper.Attachment | null = null;
export function attachment_Test_ConceptA_PropertiesMapInt8String(): dsviper.Attachment {
    if (_attachment_Test_ConceptA_PropertiesMapInt8String === null) { _attachment_Test_ConceptA_PropertiesMapInt8String = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesMapInt8String); }
    return _attachment_Test_ConceptA_PropertiesMapInt8String;
}

let _attachment_Test_ConceptA_PropertiesSeInt8: dsviper.Attachment | null = null;
export function attachment_Test_ConceptA_PropertiesSeInt8(): dsviper.Attachment {
    if (_attachment_Test_ConceptA_PropertiesSeInt8 === null) { _attachment_Test_ConceptA_PropertiesSeInt8 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesSeInt8); }
    return _attachment_Test_ConceptA_PropertiesSeInt8;
}

let _attachment_Test_ConceptA_PropertiesXArray: dsviper.Attachment | null = null;
export function attachment_Test_ConceptA_PropertiesXArray(): dsviper.Attachment {
    if (_attachment_Test_ConceptA_PropertiesXArray === null) { _attachment_Test_ConceptA_PropertiesXArray = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptA_PropertiesXArray); }
    return _attachment_Test_ConceptA_PropertiesXArray;
}

let _attachment_Test_ConceptB_PropertiesB: dsviper.Attachment | null = null;
export function attachment_Test_ConceptB_PropertiesB(): dsviper.Attachment {
    if (_attachment_Test_ConceptB_PropertiesB === null) { _attachment_Test_ConceptB_PropertiesB = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptB_PropertiesB); }
    return _attachment_Test_ConceptB_PropertiesB;
}

let _attachment_Test_ConceptC_PropertiesC: dsviper.Attachment | null = null;
export function attachment_Test_ConceptC_PropertiesC(): dsviper.Attachment {
    if (_attachment_Test_ConceptC_PropertiesC === null) { _attachment_Test_ConceptC_PropertiesC = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptC_PropertiesC); }
    return _attachment_Test_ConceptC_PropertiesC;
}

let _attachment_Test_ConceptCoverage_DocAny: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocAny(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocAny === null) { _attachment_Test_ConceptCoverage_DocAny = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAny); }
    return _attachment_Test_ConceptCoverage_DocAny;
}

let _attachment_Test_ConceptCoverage_DocAnyConceptKey: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocAnyConceptKey(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocAnyConceptKey === null) { _attachment_Test_ConceptCoverage_DocAnyConceptKey = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocAnyConceptKey); }
    return _attachment_Test_ConceptCoverage_DocAnyConceptKey;
}

let _attachment_Test_ConceptCoverage_DocBlob: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocBlob(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocBlob === null) { _attachment_Test_ConceptCoverage_DocBlob = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlob); }
    return _attachment_Test_ConceptCoverage_DocBlob;
}

let _attachment_Test_ConceptCoverage_DocBlobId: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocBlobId(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocBlobId === null) { _attachment_Test_ConceptCoverage_DocBlobId = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBlobId); }
    return _attachment_Test_ConceptCoverage_DocBlobId;
}

let _attachment_Test_ConceptCoverage_DocBool: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocBool(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocBool === null) { _attachment_Test_ConceptCoverage_DocBool = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocBool); }
    return _attachment_Test_ConceptCoverage_DocBool;
}

let _attachment_Test_ConceptCoverage_DocClubKey: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocClubKey(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocClubKey === null) { _attachment_Test_ConceptCoverage_DocClubKey = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocClubKey); }
    return _attachment_Test_ConceptCoverage_DocClubKey;
}

let _attachment_Test_ConceptCoverage_DocCommitId: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocCommitId(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocCommitId === null) { _attachment_Test_ConceptCoverage_DocCommitId = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocCommitId); }
    return _attachment_Test_ConceptCoverage_DocCommitId;
}

let _attachment_Test_ConceptCoverage_DocConceptKey: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocConceptKey(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocConceptKey === null) { _attachment_Test_ConceptCoverage_DocConceptKey = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocConceptKey); }
    return _attachment_Test_ConceptCoverage_DocConceptKey;
}

let _attachment_Test_ConceptCoverage_DocDouble: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocDouble(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocDouble === null) { _attachment_Test_ConceptCoverage_DocDouble = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocDouble); }
    return _attachment_Test_ConceptCoverage_DocDouble;
}

let _attachment_Test_ConceptCoverage_DocEnumeration: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocEnumeration(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocEnumeration === null) { _attachment_Test_ConceptCoverage_DocEnumeration = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocEnumeration); }
    return _attachment_Test_ConceptCoverage_DocEnumeration;
}

let _attachment_Test_ConceptCoverage_DocFloat: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocFloat(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocFloat === null) { _attachment_Test_ConceptCoverage_DocFloat = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocFloat); }
    return _attachment_Test_ConceptCoverage_DocFloat;
}

let _attachment_Test_ConceptCoverage_DocInt16: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocInt16(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocInt16 === null) { _attachment_Test_ConceptCoverage_DocInt16 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt16); }
    return _attachment_Test_ConceptCoverage_DocInt16;
}

let _attachment_Test_ConceptCoverage_DocInt32: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocInt32(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocInt32 === null) { _attachment_Test_ConceptCoverage_DocInt32 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt32); }
    return _attachment_Test_ConceptCoverage_DocInt32;
}

let _attachment_Test_ConceptCoverage_DocInt64: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocInt64(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocInt64 === null) { _attachment_Test_ConceptCoverage_DocInt64 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt64); }
    return _attachment_Test_ConceptCoverage_DocInt64;
}

let _attachment_Test_ConceptCoverage_DocInt8: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocInt8(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocInt8 === null) { _attachment_Test_ConceptCoverage_DocInt8 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocInt8); }
    return _attachment_Test_ConceptCoverage_DocInt8;
}

let _attachment_Test_ConceptCoverage_DocMap: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocMap(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocMap === null) { _attachment_Test_ConceptCoverage_DocMap = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMap); }
    return _attachment_Test_ConceptCoverage_DocMap;
}

let _attachment_Test_ConceptCoverage_DocMat: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocMat(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocMat === null) { _attachment_Test_ConceptCoverage_DocMat = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocMat); }
    return _attachment_Test_ConceptCoverage_DocMat;
}

let _attachment_Test_ConceptCoverage_DocOptional: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocOptional(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocOptional === null) { _attachment_Test_ConceptCoverage_DocOptional = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocOptional); }
    return _attachment_Test_ConceptCoverage_DocOptional;
}

let _attachment_Test_ConceptCoverage_DocSet: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocSet(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocSet === null) { _attachment_Test_ConceptCoverage_DocSet = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocSet); }
    return _attachment_Test_ConceptCoverage_DocSet;
}

let _attachment_Test_ConceptCoverage_DocString: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocString(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocString === null) { _attachment_Test_ConceptCoverage_DocString = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocString); }
    return _attachment_Test_ConceptCoverage_DocString;
}

let _attachment_Test_ConceptCoverage_DocStructureSingleField: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocStructureSingleField(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocStructureSingleField === null) { _attachment_Test_ConceptCoverage_DocStructureSingleField = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocStructureSingleField); }
    return _attachment_Test_ConceptCoverage_DocStructureSingleField;
}

let _attachment_Test_ConceptCoverage_DocTuple: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocTuple(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocTuple === null) { _attachment_Test_ConceptCoverage_DocTuple = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocTuple); }
    return _attachment_Test_ConceptCoverage_DocTuple;
}

let _attachment_Test_ConceptCoverage_DocUInt16: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocUInt16(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocUInt16 === null) { _attachment_Test_ConceptCoverage_DocUInt16 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt16); }
    return _attachment_Test_ConceptCoverage_DocUInt16;
}

let _attachment_Test_ConceptCoverage_DocUInt32: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocUInt32(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocUInt32 === null) { _attachment_Test_ConceptCoverage_DocUInt32 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt32); }
    return _attachment_Test_ConceptCoverage_DocUInt32;
}

let _attachment_Test_ConceptCoverage_DocUInt64: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocUInt64(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocUInt64 === null) { _attachment_Test_ConceptCoverage_DocUInt64 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt64); }
    return _attachment_Test_ConceptCoverage_DocUInt64;
}

let _attachment_Test_ConceptCoverage_DocUInt8: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocUInt8(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocUInt8 === null) { _attachment_Test_ConceptCoverage_DocUInt8 = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUInt8); }
    return _attachment_Test_ConceptCoverage_DocUInt8;
}

let _attachment_Test_ConceptCoverage_DocUUId: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocUUId(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocUUId === null) { _attachment_Test_ConceptCoverage_DocUUId = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocUUId); }
    return _attachment_Test_ConceptCoverage_DocUUId;
}

let _attachment_Test_ConceptCoverage_DocVariant: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocVariant(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocVariant === null) { _attachment_Test_ConceptCoverage_DocVariant = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVariant); }
    return _attachment_Test_ConceptCoverage_DocVariant;
}

let _attachment_Test_ConceptCoverage_DocVec: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocVec(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocVec === null) { _attachment_Test_ConceptCoverage_DocVec = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVec); }
    return _attachment_Test_ConceptCoverage_DocVec;
}

let _attachment_Test_ConceptCoverage_DocVector: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocVector(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocVector === null) { _attachment_Test_ConceptCoverage_DocVector = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocVector); }
    return _attachment_Test_ConceptCoverage_DocVector;
}

let _attachment_Test_ConceptCoverage_DocXArray: dsviper.Attachment | null = null;
export function attachment_Test_ConceptCoverage_DocXArray(): dsviper.Attachment {
    if (_attachment_Test_ConceptCoverage_DocXArray === null) { _attachment_Test_ConceptCoverage_DocXArray = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_ConceptCoverage_DocXArray); }
    return _attachment_Test_ConceptCoverage_DocXArray;
}

let _attachment_Test_Klub_PropertiesD: dsviper.Attachment | null = null;
export function attachment_Test_Klub_PropertiesD(): dsviper.Attachment {
    if (_attachment_Test_Klub_PropertiesD === null) { _attachment_Test_Klub_PropertiesD = md.definitions().checkAttachment(md.AttachmentRuntimeIds.Test_Klub_PropertiesD); }
    return _attachment_Test_Klub_PropertiesD;
}
