[project]
definitions = "definitions"
infrastructure = "topology"

[generator]
templates = "2"
manifests = ["../templates/features.json"]

[target.cpp]
features = ["TestApp", "AttachmentPool", "PoolRemote"]
output = "cpp/generated"

[target.python]
features = ["Base", "Pool", "Wheel"]
output = "python/generated"

[target.typescript]
features = ["Base", "Pool", "Package"]
output = "typescript/generated"
