[project]
definitions = "definitions"
infrastructure = "topology"

[generator]
templates = "2"
manifests = ["../templates/features.json"]

[target.cpp]
features = ["TestApp", "PoolRemote"]
output = "cpp/generated"
clean = true

[target.python]
features = ["Base", "Pool", "Wheel"]                 # Base brings Paths, which brings Fields
output = "python/generated"

[target.typescript]
features = ["Base", "Pool", "Package"]               # Base brings Paths, which brings Fields
output = "typescript/generated"
