[project]
definitions = "all.dsm"
infrastructure = "features"

[generator]
templates = "2"
manifests = ["../templates/features.json"]

[target.cpp]
features = ["TestApp", "TestBridges"]
output = "cpp/generated"
clean = true

[target.python]
features = ["Base", "Pool", "Wheel", "Fields"]
output = "python/generated"

[target.typescript]
features = ["Base", "Pool", "Package", "Fields"]
output = "typescript/generated"
