// modèle Topology — le modèle, en octets.
//
// LE .DSM EMBARQUÉ TEL QUEL, compressé et encodé. Le générateur ne produit aucun code
// d'enregistrement de types : le document est embarqué et décodé au chargement.
//
// Produit par `cpp/link/resources.py`. Ce n'est pas un texte écrit à la main.

export const B64_DEFINITIONS =
    "BAkAAAAAAAAAAR4N/Lr+VoTekEpXSnAT4xuKUw2kB/K2xRtIQo4LpMIa/8RsDgYAAAAAAAAATW9kZWxCDggAAAAAAAAA" +
    "TWF0ZXJpYWwOJgAAAAAAAABBIG1hdGVyaWFsLCBhcyBNb2RlbEIgdW5kZXJzdGFuZHMgb25lLgAAAR4N3kKryT/WrBBj" +
    "utDW+6bLng2MJMG5z79PP4l9Q/1oTRQNDgYAAAAAAAAATW9kZWxBDggAAAAAAAAATWF0ZXJpYWwOJgAAAAAAAABBIG1h" +
    "dGVyaWFsLCBhcyBNb2RlbEEgdW5kZXJzdGFuZHMgb25lLgAAAR4N1PLpaDkKrR+D1ADnL9MKUA3scoN90zVMEqSdSaUm" +
    "labbDgoAAAAAAAAAUHJvamVjdGlvbg4EAAAAAAAAAExpbmsOLgAAAAAAAABXaGF0IG9uZSBsaW5rIGJldHdlZW4gdHdv" +
    "IGRyaXZlciBtYXRlcmlhbHMgaXMuAAABHg1NHkoM4mKESdeSRO5aors/Dexyg33TNUwSpJ1JpSaVptsOCgAAAAAAAABQ" +
    "cm9qZWN0aW9uDg8AAAAAAAAARGVyaXZlZE1hdGVyaWFsDjIAAAAAAAAAQSBjb25jZXB0IHdob3NlIHBhcmVudCBsaXZl" +
    "cyBpbiBhbm90aGVyIG5hbWVzcGFjZS4AAQEeDd5Cq8k/1qwQY7rQ1vumy54BHg0leIinhIxFaFJY+IIr5hqwDT0icaKw" +
    "8U5Fm7kNMs7VudYOBgAAAAAAAABNb2RlbEMOBgAAAAAAAABNYXJrZXIOQAAAAAAAAABTb21ldGhpbmcgYSBwcm9qZWN0" +
    "aW9uIGNhbiBwb2ludCBhdCwgYW5kIG5vdGhpbmcgZWxzZSByZWZlcnMgdG8uAAABGw3MEBuG/F+FWrD2WYRLn14+DYwk" +
    "wbnPv08/iX1D/WhNFA0OBgAAAAAAAABNb2RlbEEOBgAAAAAAAABGaW5pc2gOBgEAAAAAAABVbiB0eXBlIMOpbnVtw6ly" +
    "w6ksIHBvdXIgcXVlIGxlcyB0ZW1wbGF0ZXMgZW4gcmVuY29udHJlbnQgdW4uIEF1Y3VuIGF1dHJlIG5hbWVzcGFjZQpu" +
    "J2VuIGTDqWNsYXJlLCBldCBjJ2VzdCB2b3VsdSA6IGNlIHF1aSBlc3QgdGVzdMOpIGljaSBlc3QgbGEgdG9wb2xvZ2ll" +
    "LCBwYXMgbGUgc3lzdMOobWUgZGUKdHlwZXMgLS0gbWFpcyB1bmUgY291Y2hlIHF1aSBuZSBzYWl0IHBhcyBzw6lyaWFs" +
    "aXNlciB1bmUgw6ludW3DqXJhdGlvbiBlc3QgaW5jb21wbMOodGUuBAIAAAAAAAAADgUAAAAAAAAAbWF0dGUOAAAAAAAA" +
    "AAAOBQAAAAAAAABnbG9zcw4AAAAAAAAAAAEcDadfX77jEMymugycdjlC5GENpAfytsUbSEKOC6TCGv/EbA4GAAAAAAAA" +
    "AE1vZGVsQg4GAAAAAAAAAENvbG91cg5OAAAAAAAAAENvbG91ciBpbiBmbG9hdGluZyBwb2ludCAtLSB0aGUgc2FtZSBu" +
    "YW1lIGFzIE1vZGVsQTo6Q29sb3VyLCBhIGRpZmZlcmVudCB0eXBlLgQDAAAAAAAAAA4BAAAAAAAAAHIOAAAAAAAAAAAB" +
    "CgAADgEAAAAAAAAAZw4AAAAAAAAAAAEKAAAOAQAAAAAAAABiDgAAAAAAAAAAAQoAAAEcDZuQLfIKvO+o3Jjp3oOxx6sN" +
    "7HKDfdM1TBKknUmlJpWm2w4KAAAAAAAAAFByb2plY3Rpb24OBAAAAAAAAABQYWlyDkUAAAAAAAAAVHdvIGtleXMgZnJv" +
    "bSB0d28gbmFtZXNwYWNlcyBpbiBvbmUgc3RydWN0dXJlIC0tIHRoZSBrZXk8TlM6OkM+IGVkZ2UuBAIAAAAAAAAADgEA" +
    "AAAAAAAAYQ4AAAAAAAAAAAEdAR4N3kKryT/WrBBjutDW+6bLngAADgEAAAAAAAAAYg4AAAAAAAAAAAEdAR4N/Lr+VoTe" +
    "kEpXSnAT4xuKUwAAARwNiHp4yAf/PIqBcv9a44Hf2Q2MJMG5z79PP4l9Q/1oTRQNDgYAAAAAAAAATW9kZWxBDgYAAAAA" +
    "AAAAQ29sb3VyDk4AAAAAAAAAQ29sb3VyIGluIDgtYml0IGNoYW5uZWxzIC0tIHRoZSBzYW1lIG5hbWUgYXMgTW9kZWxC" +
    "OjpDb2xvdXIsIGEgZGlmZmVyZW50IHR5cGUuBAMAAAAAAAAADgEAAAAAAAAAcg4AAAAAAAAAAAECAAAOAQAAAAAAAABn" +
    "DgAAAAAAAAAAAQIAAA4BAAAAAAAAAGIOAAAAAAAAAAABAgAABAcAAAAAAAAADaQH8rbFG0hCjgukwhr/xGwOBgAAAAAA" +
    "AABNb2RlbEIOBgAAAAAAAABjb2xvdXIBHg38uv5WhN6QSldKcBPjG4pTARwNp19fvuMQzKa6DJx2OULkYQ4AAAAAAAAA" +
    "AA0J7rP3sKaa2agP0qhQcOwIDexyg33TNUwSpJ1JpSaVptsOCgAAAAAAAABQcm9qZWN0aW9uDgQAAAAAAAAAcGFpcgEe" +
    "DdTy6Wg5Cq0fg9QA5y/TClABHA2bkC3yCrzvqNyY6d6DscerDgAAAAAAAAAADSsEtXuWd+IJYACRxInYEyMN7HKDfdM1" +
    "TBKknUmlJpWm2w4KAAAAAAAAAFByb2plY3Rpb24OBgAAAAAAAABtYXJrZXIBHg3U8uloOQqtH4PUAOcv0wpQAR0BHg0l" +
    "eIinhIxFaFJY+IIr5hqwDkMAAAAAAAAAVGhlIG9ubHkgcmVmZXJlbmNlIHRvIE1vZGVsQyBhbnl3aGVyZTogYW4gYXR0" +
    "YWNobWVudCBkb2N1bWVudCB0eXBlLg1bfbIN/mAsliBs7GaGtGgiDeXC2R6dCUUdsOzTjRRcJWwOCwAAAAAAAABBbm5v" +
    "dGF0aW9ucw4EAAAAAAAAAG5vdGUBHg38uv5WhN6QSldKcBPjG4pTAQ8OzAAAAAAAAABUaGUgc2FtZSBhdHRhY2htZW50" +
    "IG5hbWUsIG9uIHRoZSBzYW1lLW5hbWVkIGNvbmNlcHQgb2YgYW5vdGhlciBuYW1lc3BhY2UuIFRoZQpnZW5lcmF0b3Ig" +
    "cXVhbGlmaWVzIGJvdGggc2NvcGVzIHJhdGhlciB0aGFuIGNvbGxpZGluZyAtLSBidXQgb25seSBvbmNlIHRoaXMgc2Vj" +
    "b25kCm9uZSBleGlzdHMsIHNvIGFkZGluZyBpdCByZW5hbWVzIHRoZSBmaXJzdC4NoDKoI3epO3htNMg2cGl/2Q3lwtke" +
    "nQlFHbDs040UXCVsDgsAAAAAAAAAQW5ub3RhdGlvbnMOBAAAAAAAAABub3RlAR4N3kKryT/WrBBjutDW+6bLngEPDjkA" +
    "AAAAAAAAQSBub3RlIGNhcnJpZWQgYnkgYSBtYXRlcmlhbCB0aGlzIG5hbWVzcGFjZSBkb2VzIG5vdCBvd24uDan8YaTM" +
    "mxhnKZfj5Y4+5sMN7HKDfdM1TBKknUmlJpWm2w4KAAAAAAAAAFByb2plY3Rpb24OBwAAAAAAAABtYXBwaW5nAR4N1PLp" +
    "aDkKrR+D1ADnL9MKUAEXAR0BHg3eQqvJP9asEGO60Nb7psueAR0BHg38uv5WhN6QSldKcBPjG4pTDkwAAAAAAAAAQSBj" +
    "b250YWluZXIgc2hhcGUgc3Bhbm5pbmcgdHdvIG5hbWVzcGFjZXM6IG9uZSB0eXBlU3VmZml4LCBvd25lZCBieSBuZWl0" +
    "aGVyLg3kRhPOraDIoqnRILBK5EPADYwkwbnPv08/iX1D/WhNFA0OBgAAAAAAAABNb2RlbEEOBgAAAAAAAABjb2xvdXIB" +
    "Hg3eQqvJP9asEGO60Nb7psueARwNiHp4yAf/PIqBcv9a44Hf2Q4AAAAAAAAAAA369ljqVYaJCgxKXNLJIJso";
